/* Drinksbogen – opskrifter
   Felter:
   n navn · c kategori · b base · g glas · m metode · ice (null | cubes | big | crushed)
   col væskefarver (top → bund) · lay lagdelt · foam skumfarve · gar pynt (til billedet)
   i ingredienser [mængde, enhed, navn]  (enhed "top" = toppes op til sidst, "float" = lægges ovenpå)
   gt pynt-tekst · rim kant · rinse skyl glasset · mud hvad der moses · diff sværhed 1–3 · str styrke 0–3
   d beskrivelse · t tip · s egne trin (erstatter de automatiske)
*/
window.DRINKS = [
/* ---------------- Klassikere ---------------- */
{n:"Dry Martini",c:"klassiker",b:"gin",g:"martini",m:"stir",ice:null,col:["#EEF3E6"],gar:["olive"],
 i:[[6,"cl","gin"],[1,"cl","tør vermouth"],[1,"dash","appelsinbitter (valgfri)"]],gt:"en oliven på et spyd eller en tynd citronskal",diff:2,str:3,
 d:"Den mest ikoniske cocktail af dem alle: iskold, tør og elegant.",t:"Jo koldere, jo bedre. Opbevar gerne ginen i fryseren. Vil du have den endnu tørrere, så brug kun 0,5 cl vermouth."},
{n:"Manhattan",c:"klassiker",b:"whisky",g:"coupe",m:"stir",ice:null,col:["#9A3A1C","#7A2A12"],gar:["cherry"],
 i:[[5,"cl","rye whiskey"],[2,"cl","sød rød vermouth"],[2,"dash","Angostura bitter"]],gt:"et cocktailkirsebær",diff:2,str:3,
 d:"En blød og kraftfuld klassiker fra New York med whiskey, vermouth og bitter.",t:"Rye giver en krydret Manhattan, bourbon en rundere og sødere. Begge dele er rigtige."},
{n:"Old Fashioned",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:"big",col:["#C0702A","#9C5418"],gar:["orangepeel","cherry"],
 i:[[6,"cl","bourbon"],[1,"cl","sukkerlage (1:1)"],[3,"dash","Angostura bitter"]],gt:"en bred appelsinskal. Vrid den over glasset, så olierne spruttes ud, og læg den i",diff:1,str:3,
 d:"Verdens første 'cocktail': spiritus, sukker, bitter og is. Enkelt og perfekt.",t:"Brug én stor isterning. Den smelter langsomt, så drinken ikke bliver vandet."},
{n:"Negroni",c:"klassiker",b:"gin",g:"rocks",m:"stir",ice:"big",col:["#C8192E","#A5121F"],gar:["orange"],
 i:[[3,"cl","gin"],[3,"cl","Campari"],[3,"cl","sød rød vermouth"]],gt:"en halv appelsinskive",diff:1,str:3,
 d:"Italiensk aperitif i lige dele: bitter, sød og tør på samme tid.",t:"Lige dele gør den nem at huske. Prøv at skifte ginen ud med mezcal for en røget udgave."},
{n:"Boulevardier",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:"big",col:["#98221F","#7A1616"],gar:["orangepeel"],
 i:[[4.5,"cl","bourbon"],[3,"cl","Campari"],[3,"cl","sød rød vermouth"]],gt:"en appelsinskal",diff:1,str:3,
 d:"Negronis varme fætter, hvor ginen er skiftet ud med bourbon.",t:"Perfekt om efteråret. Kan også serveres uden is i et afkølet coupeglas."},
{n:"Americano",c:"long",b:"likoer",g:"highball",m:"build",ice:"cubes",col:["#E0553A","#C8392A"],gar:["orange"],
 i:[[3,"cl","Campari"],[3,"cl","sød rød vermouth"],[null,"top","danskvand (ca. 8 cl)"]],gt:"en appelsinskive",diff:1,str:1,
 d:"Let, bitter og boblende. Forløberen for Negroni og en perfekt eftermiddagsdrink.",t:"Hæld danskvanden ned langs en barske, så den bevarer flest mulige bobler."},
{n:"Sazerac",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:null,col:["#B0602C","#8E4A1E"],gar:["lemonpeel"],rinse:"absint",
 i:[[6,"cl","rye whiskey"],[1,"cl","sukkerlage"],[3,"dash","Peychaud's bitter"],[1,"dash","Angostura bitter"],[0.5,"cl","absint (til at skylle glasset)"]],gt:"en citronskal. Vrid den over drinken, og smid den derefter ud eller læg den på kanten",diff:3,str:3,
 d:"New Orleans' stolthed: krydret rye, anisduft og ingen is i glasset.",t:"Absinten skal kun dufte, ikke dominere. Hæld overskuddet ud, efter glasset er skyllet."},
{n:"Vieux Carré",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:"big",col:["#8A4520","#6E3214"],gar:["lemonpeel","cherry"],
 i:[[2.5,"cl","rye whiskey"],[2.5,"cl","cognac"],[2.5,"cl","sød rød vermouth"],[1,"tsk","Bénédictine"],[2,"dash","Peychaud's bitter"],[2,"dash","Angostura bitter"]],gt:"en citronskal og et cocktailkirsebær",diff:2,str:3,
 d:"Kompleks og krydret klassiker fra det franske kvarter i New Orleans.",t:"Rør længe nok, til drinken er silkeblød. Den har meget spiritus og kan tåle lidt fortynding."},
{n:"Rob Roy",c:"klassiker",b:"whisky",g:"coupe",m:"stir",ice:null,col:["#A04A22","#7E3416"],gar:["cherry"],
 i:[[5,"cl","blended scotch whisky"],[2.5,"cl","sød rød vermouth"],[2,"dash","Angostura bitter"]],gt:"et cocktailkirsebær",diff:2,str:3,
 d:"En Manhattan lavet på skotsk whisky, opkaldt efter en skotsk folkehelt.",t:"Brug en blød blended scotch. En meget røget whisky kan overdøve vermouthen."},
{n:"Martinez",c:"klassiker",b:"gin",g:"coupe",m:"stir",ice:null,col:["#A8452A","#8A3220"],gar:["orangepeel"],
 i:[[4.5,"cl","Old Tom gin (eller almindelig gin)"],[4.5,"cl","sød rød vermouth"],[1,"tsk","maraschinolikør"],[2,"dash","appelsinbitter"]],gt:"en appelsinskal",diff:2,str:2,
 d:"Martiniens forfader: rundere, sødere og mere krydret.",t:"Old Tom gin er let sødet og giver den mest historiske smag."},
{n:"Vesper",c:"klassiker",b:"gin",g:"martini",m:"shake",ice:null,col:["#F3ECCB"],gar:["lemonpeel"],
 i:[[6,"cl","gin"],[1.5,"cl","vodka"],[0.75,"cl","Lillet Blanc"]],gt:"en lang, tynd citronskal",diff:1,str:3,
 d:"James Bonds egen opfindelse fra Casino Royale: 'rystet, ikke rørt'.",t:"Rystningen giver en lidt mere luftig og kold drink med små iskrystaller. Det er meningen."},
{n:"Gibson",c:"klassiker",b:"gin",g:"martini",m:"stir",ice:null,col:["#F0F3EA"],gar:["onion"],
 i:[[6,"cl","gin"],[1,"cl","tør vermouth"]],gt:"2–3 syltede perleløg på et spyd",diff:1,str:3,
 d:"En Dry Martini med syltede perleløg i stedet for oliven. Let syrlig og umami.",t:"Et par dråber af løglagen i drinken giver ekstra dybde."},
{n:"Espresso Martini",c:"dessert",b:"vodka",g:"martini",m:"shake",ice:null,col:["#3D2415","#2A170C"],foam:"#C8A07A",gar:["coffee"],
 i:[[5,"cl","vodka"],[3,"cl","kaffelikør"],[3,"cl","frisk espresso (afkølet et øjeblik)"],[1,"cl","sukkerlage"]],gt:"3 kaffebønner på skummet",diff:2,str:2,
 d:"Kaffe og vodka i én silkeblød drink med en tyk, cremet skumkrone.",t:"Ryst ekstra hårdt i 20 sekunder. Det er rystningen, der giver det flotte skum."},
{n:"Cosmopolitan",c:"klassiker",b:"vodka",g:"martini",m:"shake",ice:null,col:["#E3405F","#C9284A"],gar:["orangepeel"],
 i:[[4,"cl","citronvodka"],[1.5,"cl","Cointreau"],[1.5,"cl","frisk limejuice"],[3,"cl","tranebærjuice"]],gt:"en flamberet appelsinskal eller en limeskive",diff:1,str:2,
 d:"Lyserød, frisk og syrlig. Kendt fra Sex and the City.",t:"Brug kun lidt tranebærjuice. Drinken skal være lyserød, ikke mørkerød."},
{n:"Gimlet",c:"klassiker",b:"gin",g:"coupe",m:"shake",ice:null,col:["#DDEBB6"],gar:["lime"],
 i:[[6,"cl","gin"],[2.5,"cl","frisk limejuice"],[1.5,"cl","sukkerlage"]],gt:"en tynd limeskive",diff:1,str:2,
 d:"Gin og lime. Oprindeligt drukket af britiske sømænd mod skørbug.",t:"Den klassiske udgave bruger 2 cl limecordial i stedet for juice og sukkerlage."},
{n:"Hanky Panky",c:"klassiker",b:"gin",g:"coupe",m:"stir",ice:null,col:["#7A301C","#5E2412"],gar:["orangepeel"],
 i:[[4.5,"cl","gin"],[4.5,"cl","sød rød vermouth"],[0.75,"cl","Fernet-Branca"]],gt:"en appelsinskal",diff:2,str:2,
 d:"Opfundet af den legendariske bartender Ada Coleman på Savoy i London.",t:"Fernet er meget bitter. Mål præcist, for lidt for meget tager over."},
{n:"Rusty Nail",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:"big",col:["#B8702A","#985A1C"],gar:["lemonpeel"],
 i:[[4.5,"cl","blended scotch whisky"],[2.5,"cl","Drambuie"]],gt:"en citronskal",diff:1,str:3,
 d:"Scotch og honningsødet whiskylikør. Varm, blød og enkel.",t:"Rør den direkte i glasset over isen. Det behøver ikke være mere besværligt."},
{n:"Godfather",c:"klassiker",b:"whisky",g:"rocks",m:"stir",ice:"big",col:["#B0622A","#8E4A1A"],gar:[],
 i:[[5,"cl","blended scotch whisky"],[2,"cl","amaretto"]],gt:"",diff:1,str:3,
 d:"Scotch med et strejf af mandel. Siges at være Marlon Brandos favorit.",t:"Skift scotch ud med vodka, så får du en 'Godmother'."},
{n:"Stinger",c:"klassiker",b:"brandy",g:"coupe",m:"shake",ice:null,col:["#DDB47C"],gar:["mint"],
 i:[[5,"cl","cognac"],[2,"cl","hvid crème de menthe"]],gt:"en lille myntetop",diff:1,str:3,
 d:"Cognac og mynte. En klassisk 'efter middagen'-drink fra 1920'erne.",t:"Kan også serveres over knust is i et lavt glas. Så bliver den friskere."},
{n:"Hemingway Daiquiri",c:"sour",b:"rom",g:"coupe",m:"shake",ice:null,col:["#F1E7C4"],gar:["lime"],
 i:[[6,"cl","lys rom"],[1.5,"cl","maraschinolikør"],[2.5,"cl","frisk grapefrugtjuice"],[1.5,"cl","frisk limejuice"]],gt:"en limeskive",diff:1,str:2,
 d:"Daiquiri uden sukker, men med grapefrugt og maraschino. Lavet til Hemingway.",t:"Er den for syrlig til dig, så tilsæt 0,5 cl sukkerlage."},
{n:"Oaxaca Old Fashioned",c:"klassiker",b:"tequila",g:"rocks",m:"stir",ice:"big",col:["#C07A36","#9E5E22"],gar:["orangepeel"],
 i:[[4.5,"cl","reposado tequila"],[1.5,"cl","mezcal"],[1,"cl","agavesirup"],[2,"dash","Angostura bitter"]],gt:"en flamberet appelsinskal",diff:2,str:3,
 d:"En moderne klassiker: Old Fashioned med tequila og røget mezcal.",t:"Hold appelsinskallen over en tændstik, og klem den, så olierne flammer op over glasset."},

/* ---------------- Sours ---------------- */
{n:"Whiskey Sour",c:"sour",b:"whisky",g:"rocks",m:"dry",ice:"cubes",col:["#E3A84E","#D08F30"],foam:"#F6EBD2",gar:["drops","cherry"],
 i:[[4.5,"cl","bourbon"],[2.5,"cl","frisk citronjuice"],[2,"cl","sukkerlage"],[1,"stk","æggehvide (ca. 2 cl, valgfri)"]],gt:"et par dråber Angostura på skummet og et cocktailkirsebær",diff:2,str:2,
 d:"Sød, syrlig og silkeblød med en luftig skumkrone.",t:"Æggehviden giver skummet. Er du bekymret, kan du bruge 2 cl kikærtevand (aquafaba) i stedet."},
{n:"Amaretto Sour",c:"sour",b:"likoer",g:"rocks",m:"dry",ice:"cubes",col:["#DD9632","#C27C1E"],foam:"#F6E8CC",gar:["lemonpeel","cherry"],
 i:[[4.5,"cl","amaretto"],[1.5,"cl","bourbon"],[3,"cl","frisk citronjuice"],[1,"cl","sukkerlage"],[1,"stk","æggehvide"]],gt:"en citronskal og et cocktailkirsebær",diff:2,str:1,
 d:"Mandelsød og frisk. Bourbon'en giver den ekstra dybde.",t:"Hvis du dropper bourbon'en, så skru ned for sukkerlagen, for amaretto er i forvejen sød."},
{n:"Pisco Sour",c:"sour",b:"brandy",g:"coupe",m:"dry",ice:null,col:["#F1E3A8"],foam:"#FBF6E6",gar:["drops"],
 i:[[6,"cl","pisco"],[3,"cl","frisk limejuice"],[2,"cl","sukkerlage"],[1,"stk","æggehvide"]],gt:"3 dråber Angostura bitter på skummet. Træk en tandstik igennem, så de bliver til små hjerter",diff:2,str:2,
 d:"Nationaldrinken i både Peru og Chile. Frisk, blomstret og skummende.",t:"Pisco er en druebrandy. Findes den ikke, kan du bruge en ung, lys cognac."},
{n:"Daiquiri",c:"sour",b:"rom",g:"coupe",m:"shake",ice:null,col:["#EEF3D2"],gar:["lime"],
 i:[[6,"cl","lys rom"],[2.5,"cl","frisk limejuice"],[1.5,"cl","sukkerlage"]],gt:"en tynd limeskive",diff:1,str:2,
 d:"Rom, lime og sukker. Bartenderens favorit-test af en god bar.",t:"Smag balancen til: den skal være frisk syrlig, men aldrig skarp."},
{n:"Margarita",c:"sour",b:"tequila",g:"margarita",m:"shake",ice:null,col:["#DFEAA4"],gar:["lime","salt"],rim:"salt",
 i:[[5,"cl","tequila blanco"],[2,"cl","Cointreau"],[1.5,"cl","frisk limejuice"]],gt:"en limeskive",diff:1,str:2,
 d:"Mexicos mest berømte drink med saltkant.",t:"Lav kun saltkant på halvdelen af glasset, så man selv kan vælge med eller uden salt."},
{n:"Tommy's Margarita",c:"sour",b:"tequila",g:"rocks",m:"shake",ice:"cubes",col:["#E6E7A4"],gar:["lime"],
 i:[[6,"cl","tequila blanco (100 % agave)"],[3,"cl","frisk limejuice"],[1.5,"cl","agavesirup"]],gt:"en limeskive",diff:1,str:2,
 d:"Den moderne Margarita uden appelsinlikør, så tequilaen får lov at skinne.",t:"Agavesirup er stærkere end sukker. Start med lidt, og smag til."},
{n:"Spicy Margarita",c:"sour",b:"tequila",g:"rocks",m:"muddle",ice:"cubes",col:["#D8E494"],gar:["jalapeno","tajin"],rim:"tajin",mud:"2–3 skiver jalapeño med agavesirupen",
 i:[[5,"cl","tequila blanco"],[2.5,"cl","frisk limejuice"],[2,"cl","agavesirup"],[3,"skive","jalapeño"]],gt:"en skive jalapeño",diff:2,str:2,
 d:"Margarita med chili. Frisk, syrlig og med et lunt spark til sidst.",t:"Fjern kernerne fra jalapeñoen, hvis du vil have den mildere."},
{n:"Sidecar",c:"sour",b:"brandy",g:"coupe",m:"shake",ice:null,col:["#E6A63E"],gar:["orangepeel","sugar"],rim:"sukker",
 i:[[5,"cl","cognac"],[2,"cl","Cointreau"],[2,"cl","frisk citronjuice"]],gt:"en appelsinskal",diff:1,str:2,
 d:"Paris i 1920'erne: cognac, appelsin og citron med sukkerkant.",t:"Sukkerkanten balancerer syren. Lav den kun på ydersiden af glasset."},
{n:"Tom Collins",c:"long",b:"gin",g:"collins",m:"shake",ice:"cubes",col:["#F4F2DA"],gar:["lemon","cherry","straw"],
 i:[[4.5,"cl","gin"],[3,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"],[null,"top","danskvand (ca. 6 cl)"]],gt:"en citronskive og et cocktailkirsebær",diff:1,str:1,
 d:"Gin-lemonade for voksne. Høj, kold og boblende.",t:"Hæld danskvanden sidst, og rør kun én gang, så boblerne bevares."},
{n:"Gin Fizz",c:"long",b:"gin",g:"highball",m:"shake",ice:null,col:["#F6F4E2"],foam:"#FBFAF2",gar:["lemon"],
 i:[[4.5,"cl","gin"],[3,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"],[null,"top","iskold danskvand (ca. 6 cl)"]],gt:"en citronskive",diff:1,str:1,
 d:"Som en Tom Collins, men serveret uden is og med mere brus.",t:"Hav danskvanden i køleskabet. Kold danskvand bruser mere."},
{n:"Ramos Gin Fizz",c:"long",b:"gin",g:"collins",m:"dry",ice:null,col:["#F8F5E8"],foam:"#FFFFFF",gar:["straw"],
 i:[[4.5,"cl","gin"],[1.5,"cl","frisk citronjuice"],[1.5,"cl","frisk limejuice"],[3,"cl","sukkerlage"],[3,"cl","piskefløde"],[1,"stk","æggehvide"],[3,"dråber","appelsinblomstvand"],[null,"top","iskold danskvand (ca. 4 cl)"]],gt:"et sugerør",diff:3,str:1,
 d:"Den berømte skum-drink fra New Orleans. Blød som en sky.",t:"Ryst længe. Hæld danskvanden langsomt i, så skummet rejser sig op over kanten."},
{n:"Clover Club",c:"sour",b:"gin",g:"coupe",m:"dry",ice:null,col:["#E86A8A","#D84E72"],foam:"#F9DCE4",gar:["raspberry"],
 i:[[4.5,"cl","gin"],[1.5,"cl","hindbærsirup"],[1.5,"cl","frisk citronjuice"],[1,"stk","æggehvide"]],gt:"2–3 friske hindbær på et spyd",diff:2,str:2,
 d:"Lyserød og skummende gin-sour med hindbær fra før forbudstiden.",t:"Ingen hindbærsirup? Mos 5 friske hindbær med 1,5 cl sukkerlage i shakeren."},
{n:"Aviation",c:"sour",b:"gin",g:"coupe",m:"shake",ice:null,col:["#BDB8E2"],gar:["cherry"],
 i:[[4.5,"cl","gin"],[1.5,"cl","maraschinolikør"],[1.5,"cl","frisk citronjuice"],[0.5,"cl","crème de violette"]],gt:"et cocktailkirsebær",diff:2,str:2,
 d:"Himmelblå og blomstret. Opkaldt efter luftfartens barndom.",t:"Crème de violette giver farven. Brug kun lidt, ellers smager det af sæbe."},
{n:"Last Word",c:"sour",b:"gin",g:"coupe",m:"shake",ice:null,col:["#CFE08C"],gar:["cherry"],
 i:[[2.25,"cl","gin"],[2.25,"cl","grøn Chartreuse"],[2.25,"cl","maraschinolikør"],[2.25,"cl","frisk limejuice"]],gt:"et cocktailkirsebær",diff:1,str:2,
 d:"Lige dele af fire ingredienser. Urteagtig, sød og syrlig.",t:"Lige dele gør den nem at skalere. Den er stærk, selvom den smager blødt."},
{n:"Paper Plane",c:"sour",b:"whisky",g:"coupe",m:"shake",ice:null,col:["#EC8C3C"],gar:[],
 i:[[2.25,"cl","bourbon"],[2.25,"cl","Aperol"],[2.25,"cl","Amaro Nonino"],[2.25,"cl","frisk citronjuice"]],gt:"en lille papirflyver på kanten, hvis du har lyst",diff:1,str:2,
 d:"Moderne klassiker fra 2008 i lige dele. Bittersød og frisk.",t:"Amaro Nonino kan erstattes af en anden blød amaro, fx Montenegro."},
{n:"Penicillin",c:"sour",b:"whisky",g:"rocks",m:"shake",ice:"big",col:["#E3B24C","#CE9A34"],gar:["ginger"],
 i:[[5,"cl","blended scotch whisky"],[2,"cl","frisk citronjuice"],[2,"cl","honning-ingefærsirup"],[0.75,"float","røget Islay-whisky"]],gt:"et stykke kandiseret ingefær",diff:2,str:2,
 d:"Honning, ingefær og citron med et lag røget whisky ovenpå. Kurerer alt.",t:"Honning-ingefærsirup: kog 1 del honning, 1 del vand og en god skive revet ingefær, og si."},
{n:"Bee's Knees",c:"sour",b:"gin",g:"coupe",m:"shake",ice:null,col:["#F3D47C"],gar:["lemonpeel"],
 i:[[5,"cl","gin"],[2,"cl","honningsirup (2 dele honning, 1 del varmt vand)"],[2,"cl","frisk citronjuice"]],gt:"en citronskal",diff:1,str:2,
 d:"Gin, honning og citron. Et udtryk fra 1920'erne for noget helt fantastisk.",t:"Rør honningen op med varmt vand først, ellers stivner den i shakeren."},
{n:"White Lady",c:"sour",b:"gin",g:"coupe",m:"dry",ice:null,col:["#F5F2E0"],foam:"#FFFFFF",gar:["lemonpeel"],
 i:[[4,"cl","gin"],[3,"cl","Cointreau"],[2,"cl","frisk citronjuice"],[1,"stk","æggehvide (valgfri)"]],gt:"en citronskal",diff:2,str:2,
 d:"Hvid, frisk og elegant. En klassiker fra Harry's Bar i Paris.",t:"Uden æggehvide bliver den klarere og mere syrlig. Begge versioner er gode."},
{n:"Corpse Reviver No. 2",c:"sour",b:"gin",g:"coupe",m:"shake",ice:null,col:["#F2EEC4"],gar:["orangepeel"],rinse:"absint",
 i:[[2.25,"cl","gin"],[2.25,"cl","Cointreau"],[2.25,"cl","Lillet Blanc"],[2.25,"cl","frisk citronjuice"],[1,"dash","absint (til at skylle glasset)"]],gt:"en appelsinskal",diff:2,str:2,
 d:"Lavet til at 'genoplive' dagen derpå. Frisk, let og med et strejf af anis.",t:"Brug kun en lille smule absint. Den skal kun dufte, ikke smage."},
{n:"New York Sour",c:"sour",b:"whisky",g:"rocks",m:"shake",ice:"cubes",col:["#6E1420","#E2A850","#D8962E"],lay:true,gar:["lemonpeel"],
 i:[[4.5,"cl","bourbon eller rye"],[2.5,"cl","frisk citronjuice"],[2,"cl","sukkerlage"],[2,"float","frugtig rødvin"]],gt:"en citronskal",diff:2,str:2,
 d:"Whiskey Sour med et flot lag rødvin ovenpå.",t:"Hæld vinen langsomt over bagsiden af en ske, så den flyder ovenpå."},
{n:"Southside",c:"sour",b:"gin",g:"coupe",m:"shake",ice:null,col:["#D2EBB4"],gar:["mint"],
 i:[[6,"cl","gin"],[2.5,"cl","frisk limejuice"],[2,"cl","sukkerlage"],[8,"blade","frisk mynte"]],gt:"et enkelt mynteblad flydende ovenpå",diff:1,str:2,
 d:"Gin og mynte. Nærmest en Mojito lavet på gin, bare serveret uden is.",t:"Dobbeltsi drinken, så der ikke kommer små stykker mynte med i glasset."},
{n:"Gin Basil Smash",c:"sour",b:"gin",g:"rocks",m:"muddle",ice:"cubes",col:["#9FD066","#86BE4C"],gar:["basil"],mud:"en god håndfuld basilikumblade med sukkerlagen i shakeren",
 i:[[6,"cl","gin"],[2.5,"cl","frisk citronjuice"],[2,"cl","sukkerlage"],[12,"blade","frisk basilikum"]],gt:"en basilikumtop",diff:2,str:2,
 d:"Knaldgrøn, frisk og fuld af basilikum. En moderne tysk klassiker.",t:"Mos basilikummen forsigtigt. Du vil have saften ud, ikke smadre bladene til bitter grønt."},
{n:"Gold Rush",c:"sour",b:"whisky",g:"rocks",m:"shake",ice:"big",col:["#E8AA40"],gar:["lemonpeel"],
 i:[[6,"cl","bourbon"],[2.25,"cl","honningsirup"],[2.25,"cl","frisk citronjuice"]],gt:"en citronskal",diff:1,str:2,
 d:"En Whiskey Sour med honning i stedet for sukker. Blød og gylden.",t:"Brug en mild blomsterhonning. Lynghonning kan blive for dominerende."},
{n:"Jack Rose",c:"sour",b:"brandy",g:"coupe",m:"shake",ice:null,col:["#E96B7E"],gar:["apple"],
 i:[[4.5,"cl","calvados (æblebrandy)"],[1.5,"cl","grenadine"],[2,"cl","frisk limejuice"]],gt:"en tynd æbleskive",diff:1,str:2,
 d:"Æblebrandy, granatæble og lime. Rosa og frisk.",t:"Hjemmelavet grenadine (granatæblejuice kogt med sukker) gør en kæmpe forskel."},
{n:"Naked and Famous",c:"sour",b:"tequila",g:"coupe",m:"shake",ice:null,col:["#F2903C"],gar:[],
 i:[[2.25,"cl","mezcal"],[2.25,"cl","gul Chartreuse"],[2.25,"cl","Aperol"],[2.25,"cl","frisk limejuice"]],gt:"",diff:1,str:2,
 d:"Røget, bittersød og urteagtig. Lige dele af fire ingredienser.",t:"Serveres uden pynt. Farven og duften er pynt nok."},
{n:"Caipirinha",c:"sour",b:"rom",g:"rocks",m:"muddle",ice:"crushed",col:["#EAF2CA"],gar:["lime"],mud:"½ lime skåret i små både sammen med rørsukkeret direkte i glasset",
 i:[[5,"cl","cachaça"],[0.5,"stk","lime i både"],[2,"tsk","rørsukker"]],gt:"en limebåd",diff:1,str:2,
 d:"Brasiliens nationaldrink: lime, sukker og cachaça over knust is.",t:"Mos hårdt nok til at få saft og olie ud af skallen, men ikke så hårdt, at det bliver bittert."},
{n:"Whiskey Smash",c:"sour",b:"whisky",g:"rocks",m:"muddle",ice:"crushed",col:["#DAA85C"],gar:["mint","lemon"],mud:"½ citron i både og 8 mynteblade med sukkerlagen i shakeren",
 i:[[6,"cl","bourbon"],[2,"cl","sukkerlage"],[0.5,"stk","citron i både"],[8,"blade","frisk mynte"]],gt:"en stor myntetop og en citronskive",diff:2,str:2,
 d:"Frisk og sommerlig. Et sted mellem en Mint Julep og en Whiskey Sour.",t:"Klap myntetoppen mellem hænderne, før du sætter den i. Så dufter den mere."},

/* ---------------- Longdrinks ---------------- */
{n:"Mojito",c:"long",b:"rom",g:"highball",m:"muddle",ice:"crushed",col:["#E6F4D8"],gar:["mint","lime","straw"],mud:"10 mynteblade og limejuicen med sukkerlagen i bunden af glasset",
 i:[[5,"cl","lys rom"],[3,"cl","frisk limejuice"],[2,"cl","sukkerlage"],[10,"blade","frisk mynte"],[null,"top","danskvand"]],gt:"en stor myntetop og en limeskive",diff:2,str:1,
 d:"Cubas friskeste drink: mynte, lime og rom med masser af knust is.",t:"Tryk mynten let. Knuste mynteblade bliver bitre."},
{n:"Gin & Tonic",c:"long",b:"gin",g:"wine",m:"build",ice:"cubes",col:["#EEF6F2"],gar:["lime","cucumber"],bubbles:true,
 i:[[5,"cl","gin"],[null,"top","tonic (ca. 15 cl)"]],gt:"en limeskive eller en tynd skive agurk",diff:1,str:1,
 d:"Verdens mest elskede longdrink. Enkel, frisk og bitter.",t:"Brug masser af is. Så smelter den langsommere, og drinken bliver ikke vandet."},
{n:"Cuba Libre",c:"long",b:"rom",g:"highball",m:"build",ice:"cubes",col:["#4A2616","#3A1C0E"],gar:["lime"],bubbles:true,
 i:[[5,"cl","lys eller gylden rom"],[1,"cl","frisk limejuice"],[null,"top","cola (ca. 12 cl)"]],gt:"en limebåd",diff:1,str:1,
 d:"Rom og cola med lime. Limen gør den til en 'Cuba Libre'.",t:"Pres limebåden ned i glasset. Det er limen, der løfter drinken."},
{n:"Dark 'n' Stormy",c:"long",b:"rom",g:"highball",m:"build",ice:"cubes",col:["#3A1A0A","#C99C5E","#D8B27A"],lay:true,gar:["lime"],
 i:[[null,"top","ginger beer (ca. 10 cl)"],[1,"cl","frisk limejuice"],[6,"float","mørk rom"]],gt:"en limebåd",diff:1,str:1,
 d:"Mørk rom svæver som en storm over krydret ginger beer.",
 s:["Fyld et highballglas helt op med isterninger.","Hæld ginger beer i, til glasset er cirka ¾ fyldt, og pres limejuicen i.","Hæld den mørke rom langsomt over bagsiden af en barske, så den lægger sig som en mørk sky øverst.","Pynt med en limebåd, og server med et sugerør, så man selv kan røre rundt."],
 t:"Den originale bruger Gosling's Black Seal-rom, men enhver mørk rom virker."},
{n:"Moscow Mule",c:"long",b:"vodka",g:"mug",m:"build",ice:"cubes",col:["#E9E2C0"],gar:["lime","mint"],
 i:[[4.5,"cl","vodka"],[1.5,"cl","frisk limejuice"],[null,"top","ginger beer (ca. 12 cl)"]],gt:"en limeskive og en myntetop",diff:1,str:1,
 d:"Vodka, ingefær og lime i det ikoniske kobberkrus.",t:"Kobberkruset holder drinken iskold. Et highballglas virker også fint."},
{n:"Paloma",c:"long",b:"tequila",g:"highball",m:"build",ice:"cubes",col:["#F7C4B6"],gar:["grapefruit","salt"],rim:"salt",bubbles:true,
 i:[[5,"cl","tequila blanco"],[1.5,"cl","frisk limejuice"],[1,"knivspids","salt"],[null,"top","grapefrugtsodavand (ca. 12 cl)"]],gt:"en grapefrugtskive",diff:1,str:1,
 d:"Mexicos egentlige yndlingsdrink: tequila og grapefrugt med salt.",t:"Friskpresset grapefrugt med danskvand og lidt sukker er endnu bedre end sodavand."},
{n:"Tequila Sunrise",c:"long",b:"tequila",g:"highball",m:"build",ice:"cubes",col:["#F9B92E","#F59A1E","#D3242F"],lay:true,gar:["orange","cherry"],
 i:[[4.5,"cl","tequila"],[9,"cl","appelsinjuice"],[1.5,"cl","grenadine"]],
 s:["Fyld et highballglas med isterninger.","Hæld tequila og appelsinjuice i, og rør rundt.","Hæld grenadinen langsomt ned langs indersiden af glasset. Den er tung og synker til bunden.","Lad være med at røre igen. Så får du den flotte solopgang fra rød til gul.","Pynt med en appelsinskive og et kirsebær."],
 gt:"en appelsinskive og et cocktailkirsebær",diff:1,str:1,
 d:"En solopgang i et glas: rød i bunden og gylden i toppen.",t:"Grenadinen skal hældes allersidst og helt langsomt."},
{n:"Screwdriver",c:"long",b:"vodka",g:"highball",m:"build",ice:"cubes",col:["#F8AE2C"],gar:["orange"],
 i:[[5,"cl","vodka"],[10,"cl","appelsinjuice, gerne friskpresset"]],gt:"en appelsinskive",diff:1,str:1,
 d:"Vodka og appelsinjuice. Så enkelt som det kan blive.",t:"Friskpresset juice gør den til en helt anden drink."},
{n:"Bloody Mary",c:"long",b:"vodka",g:"highball",m:"roll",ice:"cubes",col:["#B42A20","#9A1E16"],gar:["celery","lemon"],
 i:[[4.5,"cl","vodka"],[9,"cl","tomatjuice"],[1.5,"cl","frisk citronjuice"],[3,"dash","Worcestershire sauce"],[2,"dash","Tabasco"],[1,"knivspids","selleri-salt"],[1,"knivspids","friskkværnet sort peber"]],gt:"en selleristang og en citronbåd",diff:2,str:1,
 d:"Krydret, salt og frisk. Den klassiske brunch-drink.",t:"Smag til med mere Tabasco eller peberrod, hvis du kan lide den stærk."},
{n:"Long Island Iced Tea",c:"long",b:"vodka",g:"collins",m:"shake",ice:"cubes",col:["#A2622E","#8A4E22"],gar:["lemon","straw"],
 i:[[1.5,"cl","vodka"],[1.5,"cl","gin"],[1.5,"cl","lys rom"],[1.5,"cl","tequila"],[1.5,"cl","Cointreau"],[2.5,"cl","frisk citronjuice"],[3,"cl","sukkerlage"],[null,"top","cola (et skvæt)"]],gt:"en citronskive",diff:2,str:3,
 d:"Fem slags spiritus, der smager af iste. Stærkere end den ser ud.",t:"Den er meget stærk. Server den med et glas vand ved siden af."},
{n:"Sex on the Beach",c:"long",b:"vodka",g:"highball",m:"shake",ice:"cubes",col:["#F79B5A","#F06A4A","#DA3C4C"],gar:["orange","straw"],
 i:[[4,"cl","vodka"],[2,"cl","ferskenlikør"],[4,"cl","appelsinjuice"],[4,"cl","tranebærjuice"]],gt:"en appelsinskive",diff:1,str:1,
 d:"Frugtig og solnedgangsfarvet feriedrink.",t:"Hæld tranebærjuicen i sidst uden at ryste den med, så får du et flot farveskift."},
{n:"Harvey Wallbanger",c:"long",b:"vodka",g:"highball",m:"build",ice:"cubes",col:["#F4C94A","#F8B42C"],gar:["orange","cherry"],
 i:[[4.5,"cl","vodka"],[9,"cl","appelsinjuice"],[1.5,"float","Galliano"]],gt:"en appelsinskive og et cocktailkirsebær",diff:1,str:1,
 d:"En Screwdriver med et lag vaniljesød Galliano ovenpå. Ren 70'er.",t:"Galliano er tung og søger nedad. Hæld den helt til sidst og meget langsomt."},
{n:"Mint Julep",c:"long",b:"whisky",g:"rocks",m:"muddle",ice:"crushed",col:["#D6A95C"],gar:["mint","straw"],mud:"8 mynteblade med sukkerlagen i bunden af glasset",
 i:[[6,"cl","bourbon"],[1.5,"cl","sukkerlage"],[8,"blade","frisk mynte"]],gt:"en stor, frodig myntetop",diff:2,str:3,
 d:"Kentucky Derbyets officielle drink. Iskold bourbon og mynte.",t:"Rør, til glasset dugger på ydersiden. Det skal være helt iskoldt."},
{n:"Whisky Highball",c:"long",b:"whisky",g:"collins",m:"build",ice:"cubes",col:["#EACB8E"],gar:["lemonpeel"],bubbles:true,
 i:[[5,"cl","whisky (fx japansk eller blended scotch)"],[null,"top","iskold danskvand (ca. 15 cl)"]],gt:"en citronskal",diff:1,str:1,
 d:"Japans yndlingsdrink: whisky og danskvand, super kold og boblende.",t:"Rør isen rundt i glasset først, og hæld det smeltede vand ud. Så holder den boblerne længere."},
{n:"Pimm's Cup",c:"long",b:"likoer",g:"highball",m:"build",ice:"cubes",col:["#BE6A32","#A85622"],gar:["cucumber","strawberry","mint"],bubbles:true,
 i:[[5,"cl","Pimm's No. 1"],[null,"top","ginger ale eller lemonade (ca. 15 cl)"],[2,"skive","agurk"],[2,"stk","jordbær i skiver"],[1,"skive","appelsin"]],gt:"agurk, jordbær, appelsin og en myntetop",diff:1,str:1,
 d:"Englands sommerdrink til tennis og havefester. Fuld af frugt.",t:"Lav en kande til hele selskabet: 1 del Pimm's og 3 dele ginger ale."},
{n:"Garibaldi",c:"long",b:"likoer",g:"highball",m:"build",ice:"cubes",col:["#F4863C","#EC6A2A"],foam:"#F9B77A",gar:["orange"],
 i:[[4.5,"cl","Campari"],[12,"cl","friskpresset appelsinjuice"]],gt:"en appelsinbåd",diff:1,str:1,
 d:"Campari og 'luftig' appelsinjuice. Italiens enkleste aperitivo.",t:"Blend appelsinjuicen et par sekunder, så den bliver skummende og luftig."},
{n:"El Diablo",c:"long",b:"tequila",g:"highball",m:"build",ice:"cubes",col:["#E9CFA8","#B83A5A"],lay:true,gar:["lime"],
 i:[[4.5,"cl","tequila reposado"],[1.5,"cl","frisk limejuice"],[null,"top","ginger beer (ca. 10 cl)"],[1.5,"float","crème de cassis"]],gt:"en limebåd",diff:1,str:1,
 d:"Tequila, ingefær og solbær. Djævelsk god.",t:"Cassis'en drypper flot ned gennem drinken, hvis du hælder den på til sidst."},
{n:"Singapore Sling",c:"tropisk",b:"gin",g:"hurricane",m:"shake",ice:"cubes",col:["#F07A84","#E65A6C"],foam:"#F9C9CF",gar:["pineapple","cherry"],
 i:[[3,"cl","gin"],[1.5,"cl","Cherry Heering (kirsebærlikør)"],[0.75,"cl","Cointreau"],[0.75,"cl","Bénédictine"],[12,"cl","ananasjuice"],[1.5,"cl","frisk limejuice"],[1,"cl","grenadine"],[1,"dash","Angostura bitter"]],gt:"et stykke ananas og et cocktailkirsebær",diff:3,str:2,
 d:"Raffles Hotels legendariske lyserøde drink fra 1915.",t:"Ryst hårdt, så ananasjuicen giver et flot, let skum på toppen."},
{n:"Irish Mule",c:"long",b:"whisky",g:"mug",m:"build",ice:"cubes",col:["#E3CC96"],gar:["lime"],
 i:[[4.5,"cl","irsk whiskey"],[1.5,"cl","frisk limejuice"],[null,"top","ginger beer (ca. 12 cl)"]],gt:"en limeskive",diff:1,str:1,
 d:"Moscow Mules irske fætter med blød whiskey.",t:"Tilsæt et par dash Angostura for ekstra krydderi."},
{n:"Lillet Vive",c:"long",b:"vin",g:"wine",m:"build",ice:"cubes",col:["#F6EFD4"],gar:["cucumber","strawberry","mint"],bubbles:true,
 i:[[5,"cl","Lillet Blanc"],[null,"top","tonic (ca. 10 cl)"],[1,"skive","agurk"],[1,"stk","jordbær i skiver"],[3,"blade","mynte"]],gt:"agurk, jordbær og mynte",diff:1,str:0,
 d:"Let fransk aperitif med tonic og frisk frugt.",t:"Perfekt, når man vil have noget let, der stadig føles festligt."},
{n:"Sangria",c:"long",b:"vin",g:"wine",m:"build",ice:"cubes",col:["#852034","#6E1628"],gar:["orange","apple"],
 i:[[10,"cl","frugtig rødvin"],[2,"cl","brandy"],[2,"cl","appelsinlikør"],[3,"cl","appelsinjuice"],[1,"håndfuld","frugt i tern (æble, appelsin, fersken)"],[null,"top","danskvand eller sprite"]],gt:"frugtstykkerne fra glasset",diff:1,str:1,
 d:"Spansk sommer i et glas: rødvin med frugt og et skvæt brandy.",t:"Lav en kande og lad den trække i køleskabet i 2–4 timer, så smager frugten igennem."},

/* ---------------- Bobler ---------------- */
{n:"Aperol Spritz",c:"bobler",b:"vin",g:"wine",m:"sparkle",ice:"cubes",col:["#F57023","#EE5E16"],gar:["orange"],bubbles:true,
 i:[[6,"cl","prosecco"],[4,"cl","Aperol"],[2,"cl","danskvand"]],gt:"en halv appelsinskive",diff:1,str:1,
 d:"Italiens orange sommerdrink. Bittersød og boblende.",t:"Hæld prosecco i først, så Aperol, og til sidst danskvand. Så blandes den af sig selv."},
{n:"Hugo",c:"bobler",b:"vin",g:"wine",m:"sparkle",ice:"cubes",col:["#EFF3D8"],gar:["mint","lime"],bubbles:true,
 i:[[10,"cl","prosecco"],[3,"cl","hyldeblomstlikør eller -sirup"],[3,"cl","danskvand"],[6,"blade","frisk mynte"],[1,"skive","lime"]],gt:"mynte og en limeskive",diff:1,str:1,
 d:"Blomstret og let spritz fra Sydtyrol med hyldeblomst og mynte.",t:"Klap mynten let mellem hænderne, før den kommer i glasset."},
{n:"French 75",c:"bobler",b:"gin",g:"flute",m:"shake",ice:null,col:["#F6EAB2"],gar:["lemonpeel"],bubbles:true,
 i:[[3,"cl","gin"],[1.5,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"],[null,"top","champagne (ca. 6 cl)"]],gt:"en lang citronspiral",diff:2,str:2,
 d:"Opkaldt efter en fransk kanon: frisk, boblende og stærkere end den ser ud.",t:"Hæld champagnen langsomt, så den ikke skummer over."},
{n:"Mimosa",c:"bobler",b:"vin",g:"flute",m:"sparkle",ice:null,col:["#FCC044"],gar:["orange"],bubbles:true,
 i:[[7.5,"cl","iskold appelsinjuice"],[7.5,"cl","champagne eller cava"]],gt:"en lille appelsinskive på kanten",diff:1,str:1,
 d:"Brunchens dronning: lige dele bobler og appelsinjuice.",t:"Hæld bobler i først og juice bagefter, så skummer det mindre."},
{n:"Bellini",c:"bobler",b:"vin",g:"flute",m:"sparkle",ice:null,col:["#FACBA2"],gar:["peach"],bubbles:true,
 i:[[5,"cl","hvid ferskenpuré"],[10,"cl","iskold prosecco"]],gt:"en ferskenbåd",diff:1,str:1,
 d:"Fersken og prosecco. Opfundet på Harry's Bar i Venedig.",t:"Lav selv puréen: blend modne ferskner og si dem. Så er den bedst."},
{n:"Kir Royale",c:"bobler",b:"vin",g:"flute",m:"sparkle",ice:null,col:["#B63A5E","#9A2A4A"],gar:["raspberry"],bubbles:true,
 i:[[1.5,"cl","crème de cassis"],[12,"cl","champagne"]],gt:"et hindbær eller en brombær",diff:1,str:1,
 d:"Fransk elegance: solbærlikør toppet med champagne.",t:"Med hvidvin i stedet for champagne hedder den bare 'Kir'."},
{n:"Kir",c:"bobler",b:"vin",g:"wine",m:"build",ice:null,col:["#C45E72"],gar:[],
 i:[[1.5,"cl","crème de cassis"],[9,"cl","kold, tør hvidvin (fx aligoté)"]],gt:"",diff:1,str:1,
 d:"Den klassiske franske aperitif fra Bourgogne.",t:"Brug en frisk, syrlig hvidvin, som ikke er egefadslagret."},
{n:"Champagne Cocktail",c:"bobler",b:"brandy",g:"flute",m:"sparkle",ice:null,col:["#F3DA8E"],gar:["lemonpeel"],bubbles:true,
 s:["Læg en sukkerknald i bunden af en champagneflute.","Dryp 2–3 dash Angostura bitter på sukkeret, så det bliver gennemvædet.","Hæld 1 cl cognac over.","Top langsomt op med iskold champagne. Sukkeret får drinken til at boble i lang tid.","Pynt med en citronskal."],
 i:[[1,"stk","sukkerknald"],[3,"dash","Angostura bitter"],[1,"cl","cognac"],[null,"top","champagne (ca. 10 cl)"]],gt:"en citronskal",diff:1,str:1,
 d:"Sukker, bitter og bobler. En af de allerældste cocktails.",t:"Sukkerknalden bliver ved med at lave bobler. Det er smukt at se på."},
{n:"Negroni Sbagliato",c:"bobler",b:"likoer",g:"rocks",m:"build",ice:"big",col:["#DA3830","#C6281F"],gar:["orange"],bubbles:true,
 i:[[3,"cl","Campari"],[3,"cl","sød rød vermouth"],[null,"top","prosecco (ca. 3–4 cl)"]],gt:"en halv appelsinskive",diff:1,str:1,
 d:"Den 'fejlagtige' Negroni, hvor ginen blev byttet ud med bobler.",t:"Blidere end en Negroni og perfekt til en lang aften."},
{n:"Sgroppino",c:"bobler",b:"vodka",g:"flute",m:"blend",ice:null,col:["#FAF3C8"],foam:"#FFFBEA",gar:["lemonpeel"],
 i:[[4,"spsk","citronsorbet"],[2,"cl","vodka"],[6,"cl","iskold prosecco"]],
 s:["Stil fluten i fryseren i 10 minutter.","Læg citronsorbet og vodka i en skål, og pisk det sammen, til det er glat.","Tilsæt prosecco lidt ad gangen, mens du pisker blidt, så det bliver cremet og skummende.","Hæld det i det kolde glas.","Pynt med en citronskal, og server med det samme."],
 gt:"en citronskal",diff:1,str:1,
 d:"Venetiansk dessertdrink: citronsorbet pisket med prosecco og vodka.",t:"En perfekt afslutning på en god middag i stedet for dessert."},
{n:"Porn Star Martini",c:"dessert",b:"vodka",g:"coupe",m:"shake",ice:null,col:["#F7B84A","#F2A032"],foam:"#FBE4B0",gar:["passion"],
 i:[[4,"cl","vaniljevodka"],[1.5,"cl","passionsfrugtlikør (fx Passoã)"],[3,"cl","passionsfrugtpuré"],[1.5,"cl","frisk limejuice"],[1.5,"cl","vaniljesirup"]],gt:"en halv passionsfrugt, og server et shotglas prosecco (6 cl) ved siden af",diff:2,str:2,
 d:"Tropisk, sød og syrlig med et shot bobler ved siden af.",t:"Drik prosecco'en som en 'chaser' imellem, eller hæld den i drinken."},

/* ---------------- Tropisk / Tiki ---------------- */
{n:"Mai Tai",c:"tropisk",b:"rom",g:"rocks",m:"shake",ice:"crushed",col:["#D98E38","#C47626"],gar:["mint","lime"],
 i:[[3,"cl","jamaicansk rom"],[3,"cl","rhum agricole eller gylden rom"],[1.5,"cl","orange curaçao"],[1.5,"cl","orgeat (mandelsirup)"],[3,"cl","frisk limejuice"]],gt:"en myntetop og en halv, presset limeskal (som en lille ø)",diff:2,str:2,
 d:"Tiki-kulturens konge: rom, lime og mandel. Ikke rød og ikke sød.",t:"Den ægte Mai Tai har ingen ananas eller grenadine. Den er ravfarvet."},
{n:"Piña Colada",c:"tropisk",b:"rom",g:"hurricane",m:"blend",ice:null,col:["#F8F0D2"],gar:["pineapple","cherry","umbrella"],
 i:[[5,"cl","lys rom"],[3,"cl","kokoscreme (fx Coco López)"],[9,"cl","ananasjuice"],[1.5,"cl","frisk limejuice"],[1,"kop","knust is (ca. 150 g)"]],gt:"et stykke ananas, et cocktailkirsebær og en paraply",diff:1,str:1,
 d:"Puerto Ricos cremede ferie-drink med kokos og ananas.",t:"Kokoscreme er ikke det samme som kokosmælk. Den er sødet og tykkere."},
{n:"Zombie",c:"tropisk",b:"rom",g:"tiki",m:"shake",ice:"crushed",col:["#D96C2C","#C4561E"],gar:["mint","umbrella"],
 i:[[3,"cl","gylden rom"],[3,"cl","mørk jamaicansk rom"],[1.5,"cl","overproof rom (fx 151)"],[2,"cl","frisk limejuice"],[1.5,"cl","grapefrugtjuice"],[1,"cl","kanelsirup"],[1,"cl","falernum"],[0.5,"cl","grenadine"],[1,"dash","absint"],[1,"dash","Angostura bitter"]],gt:"en stor myntetop",diff:3,str:3,
 d:"Legendarisk og berygtet stærk. Maks. to pr. person, som Don the Beachcomber sagde.",t:"Den smager af frugt, men er meget stærk. Nyd den langsomt."},
{n:"Painkiller",c:"tropisk",b:"rom",g:"tiki",m:"shake",ice:"crushed",col:["#F3C77C"],gar:["nutmeg","pineapple"],
 i:[[6,"cl","mørk rom (fx Pusser's)"],[12,"cl","ananasjuice"],[3,"cl","appelsinjuice"],[3,"cl","kokoscreme"]],gt:"friskrevet muskatnød og et stykke ananas",diff:1,str:2,
 d:"Blød og cremet rom-drink fra De Britiske Jomfruøer.",t:"Muskatnødden på toppen er ikke valgfri. Den gør drinken."},
{n:"Hurricane",c:"tropisk",b:"rom",g:"hurricane",m:"shake",ice:"cubes",col:["#F0643E","#DE4630"],gar:["orange","cherry"],
 i:[[5,"cl","lys rom"],[5,"cl","mørk rom"],[5,"cl","passionsfrugtsirup"],[3,"cl","appelsinjuice"],[1.5,"cl","frisk limejuice"],[1,"cl","grenadine"]],gt:"en appelsinskive og et cocktailkirsebær",diff:1,str:3,
 d:"New Orleans' rødorange partydrink i det kurvede glas.",t:"Der er meget rom i. Del den gerne med en ven."},
{n:"Blue Hawaiian",c:"tropisk",b:"rom",g:"hurricane",m:"shake",ice:"cubes",col:["#3EBBDB","#2AA2C8"],gar:["pineapple","cherry","umbrella"],
 i:[[3,"cl","lys rom"],[3,"cl","blå curaçao"],[6,"cl","ananasjuice"],[3,"cl","kokoscreme"]],gt:"ananas, et kirsebær og en paraply",diff:1,str:1,
 d:"Knaldblå og tropisk som Stillehavet.",t:"Blend den med is, hvis du vil have en frossen udgave."},
{n:"Jungle Bird",c:"tropisk",b:"rom",g:"rocks",m:"shake",ice:"big",col:["#CE4A30","#B23822"],gar:["pineapple"],
 i:[[4.5,"cl","mørk rom"],[2.25,"cl","Campari"],[4.5,"cl","ananasjuice"],[1.5,"cl","frisk limejuice"],[1.5,"cl","demerara-sirup"]],gt:"et par ananasblade",diff:1,str:2,
 d:"Tiki møder bitter italiensk aperitivo. Opfundet i Kuala Lumpur i 1978.",t:"En kraftig, mørk rom som Blackstrap står godt op imod Campari'en."},
{n:"Planter's Punch",c:"tropisk",b:"rom",g:"highball",m:"shake",ice:"cubes",col:["#E86E3E","#D45A2C"],gar:["orange","cherry"],
 i:[[4.5,"cl","mørk rom"],[3.5,"cl","appelsinjuice"],[3.5,"cl","ananasjuice"],[2,"cl","frisk citronjuice"],[1,"cl","grenadine"],[1,"cl","sukkerlage"],[3,"dash","Angostura bitter"]],gt:"en appelsinskive og et cocktailkirsebær",diff:1,str:2,
 d:"Jamaicas klassiske rompunch: 'én sur, to søde, tre stærke, fire svage'.",t:"Lav en stor skål til fest. Den bliver kun bedre af at trække lidt."},
{n:"Navy Grog",c:"tropisk",b:"rom",g:"rocks",m:"shake",ice:"crushed",col:["#D8A456"],gar:["lime","mint"],
 i:[[3,"cl","mørk rom"],[3,"cl","gylden rom"],[2,"cl","frisk limejuice"],[2,"cl","grapefrugtjuice"],[3,"cl","honningsirup"],[null,"top","et skvæt danskvand"]],gt:"en limeskive og mynte",diff:2,str:2,
 d:"Rom, citrus og honning, inspireret af de britiske sømænds grog.",t:"Brug to forskellige romtyper. Det giver mere dybde."},
{n:"Rum Punch",c:"tropisk",b:"rom",g:"highball",m:"shake",ice:"cubes",col:["#F28A4A","#E6603A"],gar:["lime","nutmeg"],
 i:[[5,"cl","gylden rom"],[2.5,"cl","frisk limejuice"],[2,"cl","sukkerlage"],[4,"cl","ananasjuice"],[4,"cl","appelsinjuice"],[1,"cl","grenadine"]],gt:"en limeskive og lidt revet muskatnød",diff:1,str:2,
 d:"Caribisk festpunch med masser af frugt.",t:"Gang opskriften med 10 og lav den i en stor skål til havefesten."},
{n:"Missionary's Downfall",c:"tropisk",b:"rom",g:"coupe",m:"blend",ice:null,col:["#C6E6A4"],gar:["mint"],
 i:[[3,"cl","lys rom"],[1.5,"cl","ferskenlikør"],[2,"cl","frisk limejuice"],[2,"cl","honningsirup"],[3,"stk","ananasstykker"],[10,"blade","frisk mynte"],[0.5,"kop","knust is"]],gt:"en myntetop",diff:2,str:1,
 d:"Frosset mynte- og ananasfryd fra tiki-legenden Don the Beachcomber.",t:"Blend kort, så mynten ikke bliver bitter. Så forbliver den frisk og lysegrøn."},

/* ---------------- Frosne ---------------- */
{n:"Frozen Strawberry Daiquiri",c:"frossen",b:"rom",g:"hurricane",m:"blend",ice:null,col:["#EB3E56","#D62C46"],gar:["strawberry","straw"],
 i:[[5,"cl","lys rom"],[2.5,"cl","frisk limejuice"],[2,"cl","sukkerlage"],[6,"stk","jordbær (gerne frosne)"],[1,"kop","knust is"]],gt:"et jordbær på kanten",diff:1,str:1,
 d:"Iskold og knaldrød. Som en voksen jordbær-slush.",t:"Frosne jordbær giver en tykkere og koldere drink med mindre is."},
{n:"Frozen Margarita",c:"frossen",b:"tequila",g:"margarita",m:"blend",ice:null,col:["#D9EBA8"],gar:["lime","salt"],rim:"salt",
 i:[[5,"cl","tequila blanco"],[2,"cl","Cointreau"],[2.5,"cl","frisk limejuice"],[1,"cl","sukkerlage"],[1,"kop","knust is"]],gt:"en limeskive",diff:1,str:2,
 d:"Margarita som slush. Perfekt en varm sommerdag.",t:"Kom lidt ekstra sukkerlage i. Kulden dæmper sødmen."},
{n:"Mudslide",c:"frossen",b:"vodka",g:"hurricane",m:"blend",ice:null,col:["#BC9670","#A07A56"],gar:["chocolate"],
 i:[[3,"cl","vodka"],[3,"cl","kaffelikør"],[3,"cl","Baileys"],[3,"cl","piskefløde"],[1,"kop","knust is"],[1,"spsk","chokoladesauce"]],gt:"chokoladesauce løbende ned ad indersiden af glasset",diff:1,str:2,
 d:"En milkshake for voksne med kaffe, chokolade og fløde.",t:"Tilsæt en kugle vaniljeis i blenderen, så bliver den endnu mere dessert-agtig."},
{n:"Frozen Piña Colada Mango",c:"frossen",b:"rom",g:"hurricane",m:"blend",ice:null,col:["#FBC04A","#F7A830"],gar:["umbrella","pineapple"],
 i:[[5,"cl","lys rom"],[3,"cl","kokoscreme"],[100,"g","frossen mango"],[6,"cl","ananasjuice"],[1.5,"cl","frisk limejuice"],[0.5,"kop","knust is"]],gt:"en paraply og et stykke ananas",diff:1,str:1,
 d:"Piña Colada med frossen mango. Gylden, tyk og tropisk.",t:"Brug frossen mango direkte fra fryseren. Så behøver du næsten ingen is."},
{n:"Frosé",c:"frossen",b:"vin",g:"wine",m:"blend",ice:null,col:["#F4A3B0"],gar:["strawberry"],
 i:[[15,"cl","rosévin frosset i isterningebakke (natten over)"],[3,"stk","jordbær"],[2,"cl","sukkerlage"],[1,"cl","frisk citronjuice"]],gt:"et jordbær",diff:1,str:1,
 d:"Frossen rosé. Sommerens mest instagramvenlige drink.",t:"Vinen fryser ikke helt fast på grund af alkoholen. Det er meningen."},

/* ---------------- Dessert / cremede ---------------- */
{n:"White Russian",c:"dessert",b:"vodka",g:"rocks",m:"build",ice:"cubes",col:["#EDE0CC","#D8C2A2","#3A1E10"],lay:true,gar:[],
 i:[[5,"cl","vodka"],[2,"cl","kaffelikør"],[3,"float","piskefløde"]],gt:"",diff:1,str:2,
 d:"The Dudes favorit fra The Big Lebowski. Kaffe, vodka og fløde.",t:"Hæld fløden over bagsiden af en ske, så den ligger smukt ovenpå, og rør selv."},
{n:"Black Russian",c:"dessert",b:"vodka",g:"rocks",m:"build",ice:"cubes",col:["#2E160A","#221006"],gar:[],
 i:[[5,"cl","vodka"],[2,"cl","kaffelikør"]],gt:"",diff:1,str:2,
 d:"Mørk og enkel: vodka og kaffelikør over is.",t:"Top med cola, så har du en 'Colorado Bulldog'-lignende drink."},
{n:"Grasshopper",c:"dessert",b:"likoer",g:"coupe",m:"shake",ice:null,col:["#A2D8A6"],gar:["mint","chocolate"],
 i:[[3,"cl","grøn crème de menthe"],[3,"cl","hvid crème de cacao"],[3,"cl","piskefløde"]],gt:"et mynteblad eller lidt revet mørk chokolade",diff:1,str:1,
 d:"Lysegrøn, cremet og smager som After Eight.",t:"Tilsæt en kugle vaniljeis og blend, så får du en 'Frozen Grasshopper'."},
{n:"Brandy Alexander",c:"dessert",b:"brandy",g:"coupe",m:"shake",ice:null,col:["#CCA682"],gar:["nutmeg"],
 i:[[3,"cl","cognac"],[3,"cl","mørk crème de cacao"],[3,"cl","piskefløde"]],gt:"friskrevet muskatnød",diff:1,str:2,
 d:"Cognac, chokolade og fløde. Den klassiske dessertcocktail.",t:"Ryst ekstra hårdt, så fløden bliver let og luftig."},
{n:"Irish Coffee",c:"varm",b:"whisky",g:"irish",m:"hot",ice:null,col:["#F4E8D2","#2E1A10","#24140A"],lay:true,gar:[],
 i:[[4,"cl","irsk whiskey"],[9,"cl","varm, stærk kaffe"],[1.5,"cl","brun sukkerlage"],[3,"cl","let pisket fløde"]],
 s:["Varm glasset op ved at fylde det med kogende vand, og hæld vandet ud efter et minut.","Hæld brun sukkerlage og whiskey i det varme glas.","Fyld op med varm, stærk kaffe til cirka 2 cm under kanten, og rør rundt, så sukkeret opløses.","Pisk fløden let, til den lige akkurat tykner, men stadig kan hældes.","Hæld fløden langsomt over bagsiden af en ske, så den lægger sig som et tykt, hvidt lag.","Rør ikke! Drik kaffen gennem den kolde fløde."],
 gt:"",diff:2,str:2,
 d:"Varm kaffe, whiskey og sukker under et lag kold fløde.",t:"Fløden må ikke være stivpisket. Den skal kunne flyde, men stadig lægge sig ovenpå."},
{n:"Hot Toddy",c:"varm",b:"whisky",g:"irish",m:"hot",ice:null,col:["#D69A4A","#C2822E"],gar:["lemon","cinnamon"],
 i:[[4.5,"cl","whisky"],[1.5,"cl","honning"],[1.5,"cl","frisk citronjuice"],[12,"cl","varmt vand (ikke kogende)"],[1,"stk","kanelstang"],[3,"stk","nelliker"]],
 s:["Varm glasset eller kruset op med kogende vand, og hæld vandet ud.","Stik nellikerne ind i en citronskive.","Kom honning, citronjuice og whisky i glasset.","Hæld varmt vand over, og rør, til honningen er opløst.","Læg citronskiven med nelliker og kanelstangen i, og lad det trække et minut, før du drikker."],
 gt:"en citronskive med nelliker og en kanelstang",diff:1,str:2,
 d:"Varm whisky med honning og citron. Den klassiske vinterkur.",t:"Brug ikke kogende vand. Det brænder aromaerne af."},
{n:"Hot Buttered Rum",c:"varm",b:"rom",g:"irish",m:"hot",ice:null,col:["#C98A44","#B0702E"],foam:"#E8C48A",gar:["cinnamon"],
 i:[[5,"cl","mørk rom"],[1,"spsk","smør"],[1,"spsk","brun farin"],[1,"knivspids","kanel, muskat og nellike"],[12,"cl","kogende vand"]],
 s:["Rør smør, brun farin og krydderier sammen til en blød smørblanding.","Varm et krus op med kogende vand, og hæld vandet ud.","Kom smørblandingen og rommen i kruset.","Hæld kogende vand over, og rør godt, til smørret er smeltet.","Pynt med en kanelstang til at røre med."],
 gt:"en kanelstang",diff:1,str:2,
 d:"Smør, brun farin, krydderier og rom. Varm og hyggelig.",t:"Lav en stor portion af smørblandingen. Den kan holde sig i køleskabet i en uge."},
{n:"Baileys Hot Chocolate",c:"varm",b:"likoer",g:"irish",m:"hot",ice:null,col:["#FFFFFF","#6A3A22","#5A2E18"],lay:true,gar:["chocolate"],
 i:[[4,"cl","Baileys"],[15,"cl","varm kakao"],[3,"cl","flødeskum"]],
 s:["Lav varm kakao af mælk og god kakao eller mørk chokolade.","Hæld Baileys i et varmt glas eller krus.","Fyld op med den varme kakao, og rør rundt.","Top med flødeskum og revet chokolade."],
 gt:"flødeskum og revet chokolade",diff:1,str:1,
 d:"Varm kakao med irsk flødelikør. Perfekt en kold vinteraften.",t:"En knivspids havsalt i kakaoen løfter chokoladesmagen."},

/* ---------------- Shots ---------------- */
{n:"B-52",c:"shot",b:"likoer",g:"shot",m:"layer",ice:null,col:["#E8A040","#CEAE86","#2A140A"],lay:true,gar:[],
 i:[[1.5,"cl","kaffelikør"],[1.5,"cl","Baileys"],[1.5,"cl","Grand Marnier"]],
 s:["Hæld kaffelikøren i bunden af shotglasset.","Hold en barske med bagsiden opad lige over væsken, og hæld Baileys meget langsomt over skeen, så den lægger sig ovenpå.","Gentag med Grand Marnier, så du får tre flotte lag.","Server med det samme."],
 gt:"",diff:3,str:2,
 d:"Tre flotte lag: kaffe, fløde og appelsin.",t:"Den tungeste væske skal altid i først. Hæld langsomt, så lagene ikke blandes."},
{n:"Kamikaze",c:"shot",b:"vodka",g:"shot",m:"shake",ice:null,col:["#ECF1C4"],gar:[],
 i:[[3,"cl","vodka"],[3,"cl","Cointreau"],[3,"cl","frisk limejuice"]],gt:"",diff:1,str:2,
 d:"Friske, syrlige shots i lige dele. Opskriften giver 2–3 shots.",t:"Ryst den med is, så den er iskold, når den skal drikkes."},
{n:"Baby Guinness",c:"shot",b:"likoer",g:"shot",m:"layer",ice:null,col:["#EFE2C8","#2A140A","#200E06"],lay:true,gar:[],
 i:[[2.5,"cl","kaffelikør"],[1,"cl","Baileys"]],
 s:["Hæld kaffelikøren i shotglasset, så det er cirka ¾ fyldt.","Hold en ske med bagsiden opad lige over væsken.","Hæld Baileys meget langsomt over skeen, så den lægger sig ovenpå som skummet på en Guinness."],
 gt:"",diff:2,str:1,
 d:"Ligner en mini-Guinness, men smager af kaffe og fløde.",t:"Kølig Baileys lægger sig pænere ovenpå."},
{n:"Green Tea Shot",c:"shot",b:"whisky",g:"shot",m:"shake",ice:null,col:["#CCD874"],gar:[],
 i:[[1.5,"cl","irsk whiskey"],[1.5,"cl","ferskenlikør"],[1.5,"cl","sour mix (citron + sukkerlage)"],[null,"top","et skvæt danskvand"]],gt:"",diff:1,str:1,
 d:"Smager overraskende meget af grøn te, men der er ingen te i.",t:"Opskriften giver ét stort eller to små shots."},
{n:"Lemon Drop Shot",c:"shot",b:"vodka",g:"shot",m:"shake",ice:null,col:["#F6EFA4"],gar:["sugar"],rim:"sukker",
 i:[[3,"cl","citronvodka"],[1.5,"cl","frisk citronjuice"],[1,"cl","sukkerlage"]],gt:"",diff:1,str:2,
 d:"Sød og syrlig som et citronbolsje.",t:"Sukkerkanten er halvdelen af oplevelsen."},
{n:"Tequila Slammer",c:"shot",b:"tequila",g:"shot",m:"build",ice:null,col:["#F4F2E2"],gar:[],bubbles:true,
 i:[[2.5,"cl","tequila"],[2.5,"cl","sprite eller champagne"]],
 s:["Hæld tequila i et solidt shotglas.","Top med sprite eller champagne.","Læg hånden eller en serviet over glasset, og slå det én gang let ned i bordet, så det bruser.","Drik det med det samme, mens det skummer."],
 gt:"",diff:1,str:2,
 d:"Brusende tequila, der skal drikkes, mens det skummer.",t:"Brug et tykt shotglas, der kan holde til et slag."},
{n:"Lemon Meringue Shot",c:"shot",b:"vodka",g:"shot",m:"shake",ice:null,col:["#F8EBA0"],foam:"#FFFFFF",gar:[],
 i:[[2,"cl","vaniljevodka"],[1.5,"cl","limoncello"],[1,"cl","frisk citronjuice"],[1,"cl","piskefløde"]],gt:"en lille klat flødeskum",diff:1,str:1,
 d:"Citrontærte i et shotglas.",t:"Hvis du dypper kanten i knuste kiks, bliver det endnu mere tærte-agtigt."},

/* ---------------- Flere klassikere og moderne ---------------- */
{n:"French Martini",c:"klassiker",b:"vodka",g:"martini",m:"shake",ice:null,col:["#D65474"],foam:"#F2B8C6",gar:["raspberry"],
 i:[[4.5,"cl","vodka"],[1.5,"cl","Chambord (hindbærlikør)"],[4.5,"cl","ananasjuice"]],gt:"et hindbær",diff:1,str:2,
 d:"Frugtig og skummende. Ananasjuicen giver et fint, hvidt skum.",t:"Ryst hårdt. Ananas skummer flot, når den rystes med is."},
{n:"Lemon Drop Martini",c:"sour",b:"vodka",g:"martini",m:"shake",ice:null,col:["#F5EDA0"],gar:["lemon","sugar"],rim:"sukker",
 i:[[4.5,"cl","vodka"],[2,"cl","Cointreau"],[2.5,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"]],gt:"en citronskive",diff:1,str:2,
 d:"Sød, syrlig og frisk med sukkerkant. Smager som et citronbolsje.",t:"Citronvodka giver ekstra citronsmag."},
{n:"Appletini",c:"klassiker",b:"vodka",g:"martini",m:"shake",ice:null,col:["#BDE56E"],gar:["apple"],
 i:[[4.5,"cl","vodka"],[1.5,"cl","grøn æblelikør"],[1.5,"cl","frisk citronjuice"],[1,"cl","sukkerlage"]],gt:"en tynd skive grønt æble",diff:1,str:2,
 d:"Knaldgrøn og syrlig æblemartini fra 90'erne.",t:"Pensl æbleskiven med citron, så den ikke bliver brun."},
{n:"Bramble",c:"sour",b:"gin",g:"rocks",m:"shake",ice:"crushed",col:["#5E1842","#EAE6D4"],lay:true,gar:["blackberry","lemon"],
 i:[[5,"cl","gin"],[2.5,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"],[1.5,"float","crème de mûre (brombærlikør)"]],gt:"en brombær og en citronskive",diff:1,str:2,
 d:"Moderne britisk klassiker. Brombærlikøren løber som blæk ned gennem isen.",t:"Crème de cassis kan bruges i stedet for brombærlikør."},
{n:"Porto Tonic",c:"long",b:"vin",g:"wine",m:"build",ice:"cubes",col:["#F4E6B6"],gar:["orange","mint"],bubbles:true,
 i:[[5,"cl","hvid portvin"],[null,"top","tonic (ca. 10 cl)"]],gt:"en appelsinskive og mynte",diff:1,str:0,
 d:"Portugals svar på G&T: hvid portvin med tonic.",t:"En let og lav-alkohol-drink, som er perfekt til lange sommeraftener."},
{n:"Campari Orange",c:"long",b:"likoer",g:"highball",m:"build",ice:"cubes",col:["#EE5A34","#E04A28"],gar:["orange"],
 i:[[4,"cl","Campari"],[12,"cl","appelsinjuice"]],gt:"en appelsinskive",diff:1,str:1,
 d:"Bitter og sød i perfekt balance.",t:"Friskpresset appelsin gør den meget bedre."},
{n:"Salty Dog",c:"long",b:"vodka",g:"rocks",m:"build",ice:"cubes",col:["#F7D2BE"],gar:["grapefruit","salt"],rim:"salt",
 i:[[5,"cl","vodka eller gin"],[12,"cl","grapefrugtjuice"]],gt:"en grapefrugtbåd",diff:1,str:1,
 d:"Grapefrugt og vodka med saltkant. Frisk og bitter-syrlig.",t:"Uden saltkant hedder den en 'Greyhound'."},
{n:"Sea Breeze",c:"long",b:"vodka",g:"highball",m:"build",ice:"cubes",col:["#F4B0A6","#E0485C"],gar:["lime"],
 i:[[4,"cl","vodka"],[12,"cl","tranebærjuice"],[3,"cl","grapefrugtjuice"]],gt:"en limebåd",diff:1,str:1,
 d:"Tranebær og grapefrugt. En frisk strandbrise i et glas.",t:"Byt grapefrugt ud med ananas, så får du en 'Bay Breeze'."},
{n:"Woo Woo",c:"long",b:"vodka",g:"highball",m:"build",ice:"cubes",col:["#E85468"],gar:["lime"],
 i:[[4,"cl","vodka"],[2,"cl","ferskenlikør"],[10,"cl","tranebærjuice"]],gt:"en limebåd",diff:1,str:1,
 d:"Fersken og tranebær. Sød og frugtig festdrink.",t:"Server i en kande til festen."},
{n:"Blue Lagoon",c:"long",b:"vodka",g:"highball",m:"build",ice:"cubes",col:["#4CC6E6","#36B0D6"],gar:["lemon","cherry"],bubbles:true,
 i:[[4,"cl","vodka"],[2,"cl","blå curaçao"],[null,"top","lemonade eller sprite (ca. 12 cl)"]],gt:"en citronskive og et kirsebær",diff:1,str:1,
 d:"Lyseblå som en lagune. Sød og citrusfrisk.",t:"Farven er det hele. Brug et klart glas, så den skinner."},
{n:"Cranberry Mule",c:"long",b:"vodka",g:"mug",m:"build",ice:"cubes",col:["#D84A5A"],gar:["rosemary","cranberry"],
 i:[[4.5,"cl","vodka"],[4,"cl","tranebærjuice"],[1.5,"cl","frisk limejuice"],[null,"top","ginger beer"]],gt:"en rosmarinkvist og et par tranebær",diff:1,str:1,
 d:"Julet udgave af Moscow Mule med tranebær og rosmarin.",t:"Perfekt til julefrokosten."},
{n:"Ginger Rogers",c:"long",b:"gin",g:"highball",m:"muddle",ice:"cubes",col:["#E8EEC8"],gar:["mint","lime"],mud:"8 mynteblade med ingefærsirupen i shakeren",
 i:[[4.5,"cl","gin"],[2,"cl","ingefærsirup"],[2,"cl","frisk limejuice"],[8,"blade","mynte"],[null,"top","ginger ale"]],gt:"en myntetop",diff:2,str:1,
 d:"Gin, ingefær og mynte. Lige så let på tæerne som danseren.",t:"Lav selv ingefærsirup af revet ingefær kogt med sukker og vand."},
{n:"Elderflower Collins",c:"long",b:"gin",g:"collins",m:"shake",ice:"cubes",col:["#F2F4DC"],gar:["lemon","cucumber"],bubbles:true,
 i:[[4.5,"cl","gin"],[2,"cl","hyldeblomstlikør"],[2,"cl","frisk citronjuice"],[null,"top","danskvand"]],gt:"en citronskive og en agurkestrimmel",diff:1,str:1,
 d:"Nordisk sommer: gin, hyldeblomst og citron med brus.",t:"Hyldeblomstsaft (fortyndet med lidt vand) kan bruges i stedet for likør."},
{n:"Gin Rickey",c:"long",b:"gin",g:"highball",m:"build",ice:"cubes",col:["#EFF6E4"],gar:["lime"],bubbles:true,
 i:[[5,"cl","gin"],[1.5,"cl","frisk limejuice"],[null,"top","danskvand (ca. 12 cl)"]],gt:"en limebåd",diff:1,str:1,
 d:"Tør, frisk og uden sukker. Washingtons sommerdrink.",t:"Uden sukker er den meget tør. Tilsæt lidt sukkerlage, hvis du vil have den blødere."},
{n:"Rum Old Fashioned",c:"klassiker",b:"rom",g:"rocks",m:"stir",ice:"big",col:["#B8652A","#98501C"],gar:["orangepeel"],
 i:[[6,"cl","lagret mørk rom"],[0.75,"cl","demerara-sirup"],[2,"dash","Angostura bitter"],[1,"dash","appelsinbitter"]],gt:"en appelsinskal",diff:1,str:3,
 d:"Old Fashioned med lagret rom. Toner af karamel og vanilje.",t:"Brug en god rom, som du også ville drikke ren."},
{n:"Tequila Negroni",c:"klassiker",b:"tequila",g:"rocks",m:"stir",ice:"big",col:["#D02A2E","#B0181E"],gar:["grapefruit"],
 i:[[3,"cl","reposado tequila eller mezcal"],[3,"cl","Campari"],[3,"cl","sød rød vermouth"]],gt:"en grapefrugtskal",diff:1,str:3,
 d:"Negroni med agavens jordede smag.",t:"Med mezcal bliver den røget. Med tequila bliver den blødere."},
{n:"Mezcal Mule",c:"long",b:"tequila",g:"mug",m:"build",ice:"cubes",col:["#E4DAB0"],gar:["lime","cucumber"],
 i:[[4.5,"cl","mezcal"],[2,"cl","frisk limejuice"],[1,"cl","agavesirup"],[2,"skive","agurk"],[null,"top","ginger beer"]],gt:"en limeskive og en agurkeskive",diff:1,str:1,
 d:"Røget mezcal, agurk og ginger beer.",t:"Mos agurken let i bunden for mere friskhed."},
{n:"Siesta",c:"sour",b:"tequila",g:"coupe",m:"shake",ice:null,col:["#F29AA0"],gar:["grapefruit"],
 i:[[4.5,"cl","tequila blanco"],[1.5,"cl","Campari"],[1.5,"cl","frisk limejuice"],[1.5,"cl","grapefrugtjuice"],[1.5,"cl","sukkerlage"]],gt:"en grapefrugtskal",diff:1,str:2,
 d:"En bittersød tequila-sour med Campari og grapefrugt.",t:"Den er som en lyserød blanding af en Margarita og en Paloma."},
{n:"Cosmo Royale",c:"bobler",b:"vodka",g:"flute",m:"shake",ice:null,col:["#EE6A82"],gar:["orangepeel"],bubbles:true,
 i:[[3,"cl","citronvodka"],[1,"cl","Cointreau"],[1,"cl","frisk limejuice"],[2,"cl","tranebærjuice"],[null,"top","champagne"]],gt:"en appelsinskal",diff:1,str:2,
 d:"Cosmopolitan med champagne. Til fester og fejring.",t:"Ryst kun de første fire ingredienser. Champagnen kommer på til sidst."},
{n:"Aperol Sour",c:"sour",b:"likoer",g:"coupe",m:"dry",ice:null,col:["#F5854A"],foam:"#FCE3D4",gar:["orangepeel"],
 i:[[5,"cl","Aperol"],[2.5,"cl","frisk citronjuice"],[1.5,"cl","sukkerlage"],[1,"stk","æggehvide"]],gt:"en appelsinskal",diff:2,str:1,
 d:"Bittersød appelsin med en blød skumkrone. Let i alkohol.",t:"En god drink til dem, der synes, Aperol Spritz er for tynd."},
{n:"Espresso Tonic Royale",c:"long",b:"likoer",g:"highball",m:"build",ice:"cubes",col:["#6A3A20","#EEF3EE"],lay:true,gar:["orangepeel"],bubbles:true,
 i:[[12,"cl","tonic"],[2,"cl","kaffelikør"],[3,"float","afkølet espresso"]],gt:"en appelsinskal",diff:1,str:1,
 d:"Boblende tonic med kaffelikør og et lag espresso ovenpå.",t:"Hæld espressoen langsomt over en ske, så den flyder ovenpå tonicen."},
{n:"Limoncello Spritz",c:"bobler",b:"likoer",g:"wine",m:"sparkle",ice:"cubes",col:["#F8EE90"],gar:["lemon","mint"],bubbles:true,
 i:[[6,"cl","prosecco"],[4,"cl","limoncello"],[2,"cl","danskvand"]],gt:"en citronskive og mynte",diff:1,str:1,
 d:"Italiensk citronsommer med bobler.",t:"Brug en kold limoncello fra fryseren."},
{n:"Rossini",c:"bobler",b:"vin",g:"flute",m:"sparkle",ice:null,col:["#F06A7A"],gar:["strawberry"],bubbles:true,
 i:[[5,"cl","jordbærpuré"],[10,"cl","iskold prosecco"]],gt:"et jordbær på kanten",diff:1,str:1,
 d:"Bellinis jordbær-søster, opkaldt efter komponisten Rossini.",t:"Blend friske jordbær med en smule sukker, og si puréen."},

/* ---------------- Alkoholfri ---------------- */
{n:"Virgin Mojito",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"muddle",ice:"crushed",col:["#E6F4D8"],gar:["mint","lime","straw"],mud:"10 mynteblade og limejuicen med sukkerlagen i bunden af glasset",
 i:[[3,"cl","frisk limejuice"],[2.5,"cl","sukkerlage"],[10,"blade","frisk mynte"],[null,"top","danskvand eller sprite"]],gt:"en stor myntetop og en limeskive",diff:1,str:0,
 d:"Al den friske mynte og lime, men uden rom.",t:"Brug sprite i stedet for danskvand, hvis du vil have den lidt sødere."},
{n:"Virgin Piña Colada",c:"alkoholfri",b:"alkoholfri",g:"hurricane",m:"blend",ice:null,col:["#F8F0D2"],gar:["pineapple","cherry","umbrella"],
 i:[[4,"cl","kokoscreme"],[12,"cl","ananasjuice"],[1.5,"cl","frisk limejuice"],[1,"kop","knust is"]],gt:"ananas, et kirsebær og en paraply",diff:1,str:0,
 d:"Cremet kokos og ananas. Ferie for hele familien.",t:"En halv banan i blenderen gør den ekstra cremet."},
{n:"Shirley Temple",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"build",ice:"cubes",col:["#F7A2A0","#EE6E70"],gar:["cherry","lime"],bubbles:true,
 i:[[2,"cl","grenadine"],[null,"top","ginger ale (ca. 15 cl)"],[1,"cl","frisk limejuice"]],gt:"to cocktailkirsebær og en limeskive",diff:1,str:0,
 d:"Den klassiske børnecocktail, opkaldt efter barnestjernen Shirley Temple.",t:"Hæld grenadinen i sidst, så den synker og giver en flot farveovergang."},
{n:"Virgin Mary",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"roll",ice:"cubes",col:["#B42A20","#9A1E16"],gar:["celery","lemon"],
 i:[[12,"cl","tomatjuice"],[1.5,"cl","frisk citronjuice"],[3,"dash","Worcestershire sauce"],[2,"dash","Tabasco"],[1,"knivspids","selleri-salt"],[1,"knivspids","sort peber"]],gt:"en selleristang og en citronbåd",diff:1,str:0,
 d:"Bloody Mary uden vodka. Krydret og mættende.",t:"En teskefuld revet peberrod giver ekstra kant."},
{n:"Hjemmelavet Lemonade",c:"alkoholfri",b:"alkoholfri",g:"collins",m:"build",ice:"cubes",col:["#F7F2B4"],gar:["lemon","mint","straw"],
 i:[[5,"cl","frisk citronjuice"],[3.5,"cl","sukkerlage"],[null,"top","koldt vand eller danskvand (ca. 12 cl)"]],gt:"citronskiver og mynte",diff:1,str:0,
 d:"Frisk, sur og sød. Sommerens bedste tørstslukker.",t:"Lav en kande: 1 del citronjuice, 0,7 dele sukkerlage og 3 dele vand."},
{n:"Arnold Palmer",c:"alkoholfri",b:"alkoholfri",g:"collins",m:"build",ice:"cubes",col:["#D29A4A","#E8C470"],gar:["lemon"],
 i:[[10,"cl","kold iste (usødet)"],[10,"cl","lemonade"]],gt:"en citronskive",diff:1,str:0,
 d:"Halv iste, halv lemonade. Opkaldt efter golflegenden.",t:"Brug sort te, der er brygget stærkt og afkølet."},
{n:"Cranberry Fizz",c:"alkoholfri",b:"alkoholfri",g:"wine",m:"build",ice:"cubes",col:["#D83550"],gar:["rosemary","cranberry"],bubbles:true,
 i:[[8,"cl","tranebærjuice"],[2,"cl","frisk limejuice"],[1,"cl","sukkerlage"],[null,"top","danskvand"]],gt:"en rosmarinkvist og et par tranebær",diff:1,str:0,
 d:"Festlig og rubinrød. Perfekt til nytårsaften uden alkohol.",t:"Hold rosmarinen over en flamme et øjeblik, så dufter den som juletræ."},
{n:"Nojito Mule",c:"alkoholfri",b:"alkoholfri",g:"mug",m:"build",ice:"cubes",col:["#E9E2C0"],gar:["lime","mint","cucumber"],
 i:[[2,"cl","frisk limejuice"],[2,"skive","agurk"],[null,"top","ginger beer (ca. 15 cl)"]],gt:"lime, mynte og agurk",diff:1,str:0,
 d:"Alkoholfri Mule med ingefær, lime og agurk.",t:"Ginger beer er stærkere i smagen end ginger ale. Vælg efter humør."},
{n:"Passion Fruit Fizz",c:"alkoholfri",b:"alkoholfri",g:"coupe",m:"shake",ice:null,col:["#F7BA4E"],foam:"#FCE6B6",gar:["passion"],
 i:[[4,"cl","passionsfrugtpuré"],[1.5,"cl","frisk limejuice"],[1.5,"cl","vaniljesirup"],[null,"top","tonic (ca. 5 cl)"]],gt:"en halv passionsfrugt",diff:1,str:0,
 d:"Tropisk og syrlig som en Porn Star Martini, men helt uden alkohol.",t:"Ryst hårdt, så den får et fint skum."},
{n:"Espresso Tonic",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"build",ice:"cubes",col:["#6A3A20","#EEF3EE"],lay:true,gar:["orangepeel"],bubbles:true,
 i:[[12,"cl","tonic"],[4,"float","frisk espresso"]],gt:"en appelsinskal",diff:1,str:0,
 d:"Kaffebarens hippe sommerdrink: iskold tonic med espresso ovenpå.",t:"Hæld espressoen langsomt, så den lægger sig som et lag ovenpå."},
{n:"Virgin Sunrise",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"build",ice:"cubes",col:["#F9B92E","#F59A1E","#D3242F"],lay:true,gar:["orange","cherry"],
 i:[[12,"cl","appelsinjuice"],[1.5,"cl","grenadine"]],
 s:["Fyld et highballglas med is.","Hæld appelsinjuicen i.","Hæld grenadinen langsomt ned langs indersiden af glasset, så den synker til bunden.","Pynt med en appelsinskive og et kirsebær."],
 gt:"en appelsinskive og et kirsebær",diff:1,str:0,
 d:"Solopgang uden tequila. Børnene elsker den.",t:"Rør ikke rundt. Så bevares farverne."},
{n:"Elderflower Cooler",c:"alkoholfri",b:"alkoholfri",g:"collins",m:"build",ice:"cubes",col:["#EFF3D8"],gar:["cucumber","lime","mint"],bubbles:true,
 i:[[3,"cl","hyldeblomstsaft"],[1.5,"cl","frisk limejuice"],[3,"skive","agurk"],[null,"top","danskvand"]],gt:"agurk, lime og mynte",diff:1,str:0,
 d:"Dansk sommer: hyldeblomst, agurk og lime med brus.",t:"Brug hjemmelavet hyldeblomstsaft fra juni. Den er den bedste."},
{n:"Strawberry Basil Smash",c:"alkoholfri",b:"alkoholfri",g:"rocks",m:"muddle",ice:"cubes",col:["#EC5A70"],gar:["strawberry","basil"],mud:"3 jordbær og 5 basilikumblade med sukkerlagen i shakeren",
 i:[[3,"stk","jordbær"],[5,"blade","basilikum"],[2,"cl","frisk citronjuice"],[2,"cl","sukkerlage"],[null,"top","danskvand"]],gt:"et jordbær og en basilikumtop",diff:2,str:0,
 d:"Sød jordbær og krydret basilikum. Frisk og anderledes.",t:"Dobbeltsi, så der ikke kommer kerner og bladstykker med."},
{n:"Apple Ginger Spritz",c:"alkoholfri",b:"alkoholfri",g:"wine",m:"build",ice:"cubes",col:["#EDD38A"],gar:["apple","cinnamon"],bubbles:true,
 i:[[8,"cl","klar æblemost"],[1,"cl","frisk citronjuice"],[null,"top","ginger ale"]],gt:"en æbleskive og en kanelstang",diff:1,str:0,
 d:"Efterårets alkoholfri spritz med æble og ingefær.",t:"Kanelstangen giver en lun duft, når man drikker."},
{n:"Mango Lassi Colada",c:"alkoholfri",b:"alkoholfri",g:"hurricane",m:"blend",ice:null,col:["#FBC04A"],gar:["umbrella"],
 i:[[150,"g","mango (frisk eller frossen)"],[10,"cl","yoghurt naturel"],[4,"cl","kokosmælk"],[1,"spsk","honning"],[0.5,"kop","is"],[1,"knivspids","kardemomme"]],gt:"en paraply og lidt kardemomme",diff:1,str:0,
 d:"Cremet og mættende mangodrink med kokos og kardemomme.",t:"Kan også serveres som morgenmad."},
{n:"Blå Lagune (alkoholfri)",c:"alkoholfri",b:"alkoholfri",g:"highball",m:"build",ice:"cubes",col:["#6ED0EA","#44B8DA"],gar:["lemon","cherry"],bubbles:true,
 i:[[2,"cl","blå curaçao-sirup (alkoholfri)"],[1,"cl","frisk citronjuice"],[null,"top","sprite"]],gt:"en citronskive og et kirsebær",diff:1,str:0,
 d:"Knaldblå og boblende. Et hit til børnefødselsdage.",t:"Alkoholfri blå sirup findes i mange supermarkeder og kaffebarer."}
];
