/* Fotos fra Wikimedia Commons – lavet af foto-vaerktoej/saml.mjs */
window.FOTOS = {"aebleskiver":{"a":"edenpictures","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Aebelskivers_in_New_Orleans.jpg"},
"aebletaerte":{"a":"Katrin Gilger","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Apfeltarte_mit_Marzipan_(5479528100).jpg"},
"aeg-benedict":{"a":"Mark Miller","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Traditional_Eggs_Benedict.jpg"},
"aeg-og-rejer-paa-rugbroed":{"a":"Gunnar Creutz","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Stor_r%C3%A4ksm%C3%B6rg%C3%A5s_p%C3%A5_M%C3%B6ssebergsg%C3%A5rden_2591.jpg"},
"aeggekage-med-flaesk":{"a":"Kolforn","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:-2019-01-14_Bacon_and_Mushroom_Frittata,_Cromer.JPG"},
"aeggesalat":{"a":"jill, jellidonut... whatever from Raleigh, NC, USA","l":"CC BY 2.5","u":"https://commons.wikimedia.org/wiki/File:Egg_salad_sandwich_-_cropped.jpg"},
"aertesuppe-med-mynte":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Courgette,_Pea_%26_Mint_Soup_-_Brooklands_Cafe_2026-05-15.jpg"},
"afrikansk-jordnoeddegryde":{"a":"A Healthier Michigan from Detroit, United States","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:African_Chicken_Peanut_Stew_(37673757141).jpg"},
"agurkesalat":{"a":"Benreis","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Gurkensalat_Potsdam.jpg"},
"aioli":{"a":"Marianne Casamance","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:A%C3%AFoli_maison.jpg"},
"amerikanske-pandekager":{"a":"Mae Mu","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg"},
"arme-riddere":{"a":"Ocdp","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:French_toast_001.jpg"},
"avocadotoast-med-pocheret-aeg":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Smashed_Avocado_On_Toast_(with_one_poached_egg)_-_Jonny%27s_2026-01-06.jpg"},
"baba-ganoush":{"a":"Basel15 at English Wikipedia","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Baba_Ghanoush.jpg"},
"bagt-aubergine-med-tahin-og-granataeble":{"a":"HaJunkiyada","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Roasted_Eggplant_with_Tahini_and_Balsamic_Glaze.jpg"},
"bagt-havregroed-med-aeble-og-kanel":{"a":"Douglas Perkins","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Apple_Crisp.jpg"},
"bagt-torsk-med-chorizo-og-boenner":{"a":"https://www.flickr.com/photos/18472724@N00/","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Cod_with_chorizo_and_pimientos_de_padron_at_Restaurante_Ca_Pepe.jpg"},
"bananbroed":{"a":"Joost Nusselder","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Sliced_Filipino_Homemade_Banana_Bread.jpg"},
"bananpandekager-med-havregryn":{"a":"Brandon Martin-Anderson","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Banana_on_pancake.jpg"},
"banh-mi-med-svinekoed":{"a":"Andrea Nguyen","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Viet_McRib_Banh_Mi.jpg"},
"bearnaisesauce":{"a":"Sacha47","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Sauce_Bearnaise_2.jpg"},
"bibimbap-med-tofu":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Brighton_Bibimbap_(tofu)_-_Time_For_Kimchi.jpg"},
"biksemad":{"a":"Skivsamlare","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Pyttipanna.JPG"},
"bircher-musli":{"a":"David Stewart","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Muesli_with_Berries.jpg"},
"blaabaermuffins":{"a":"SKopp","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Blueberry_muffins,_whole_and_partial.jpg"},
"blomkaalsboeffer-med-chimichurri":{"a":"HaJunkiyada","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_%E2%80%93_Whole_roasted_cauliflower.jpg"},
"blomkaalssuppe-med-ristede-mandler":{"a":"Gerda Arendt","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Soup,_Paris.jpg"},
"boenneburger":{"a":"Bing from Boston, United States","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Vegetarian_black_bean_burger_with_homefries.jpg"},
"boeuf-bourguignon":{"a":"Arnaud 25","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:B%C5%93uf_bourguignon.JPG"},
"boeuf-stroganoff":{"a":"Pittaya Sroilong (original file) ; cropped and retouched by Off-shell","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Beef_Stroganoff-02_cropped.jpg"},
"boller-i-karry":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Boller_i_karry_med_ris_og_agurkesalat.jpg"},
"borsjtj":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Ukrainian_borscht.jpg"},
"braendende-kaerlighed":{"a":"Theen90","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Br%C3%A6ndende_K%C3%A6rlighed.jpg"},
"brioche":{"a":"Msayago10","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Brioche_Nanterre.jpg"},
"broccolisuppe-med-cheddar":{"a":"Ken Hawkins from SC, USA","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Brocoli_and_cheddar_soup_with_focaccia.jpg"},
"brownies":{"a":"Ukendt","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Chocolate_brownies_without_table.jpg"},
"brun-sovs":{"a":"Don Crowley","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Champ_with_pork_and_gravy_(cropped).jpg"},
"brunkager":{"a":"Turku Gingerbread from Finland","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Finnish_Gingerbread_(14795888216).jpg"},
"bruschetta-med-tomat-og-basilikum":{"a":"Abi Porter","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Tomato_and_basil_bruschetta_(4925749658).jpg"},
"bulgogi":{"a":"Debbie Tingzon","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Bulgogi_3.jpg"},
"burger":{"a":"Thogru","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Homemade_cheeseburger.jpg"},
"butter-chicken":{"a":"stu_spivack","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg"},
"cacio-e-pepe":{"a":"Popo le Chien","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Cacio_e_pepe.jpg"},
"caesarsalat":{"a":"Daderot","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Chicken_Caesar_salad_-_Auckland,_New_Zealand.jpg"},
"cannelloni-med-spinat-og-ricotta":{"a":"Francis Bijl from Groningen, Netherlands","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Cannelloni_ready_to_eat_(504724484).jpg"},
"caprese":{"a":"Rainer Zenz","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Caprese-1.jpg"},
"cheesecake":{"a":"Alice Wiegand","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Cheesecake_mit_Beeren.jpg"},
"chiagroed-med-kokos-og-mango":{"a":"Miscellaneous contributor","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Chia_seed_pudding_in_a_tea_cup.jpg"},
"chili-con-carne":{"a":"Carstor","l":"CC BY-SA 2.5","u":"https://commons.wikimedia.org/wiki/File:Bowl_of_chili.jpg"},
"chili-sin-carne":{"a":"Benreis","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Chilli_sine_carne_Zur_Tanne_Harsdorf.jpg"},
"chocolate-chip-cookies":{"a":"Jonathunder","l":"GFDL 1.2","u":"https://commons.wikimedia.org/wiki/File:6cookies.JPG"},
"chokolademousse":{"a":"jules / stonesoup","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chocolate_mousse_-_stonesoup.jpg"},
"ciabatta":{"a":"Key West Wedding Photography","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Ciabatta_Bread.jpg"},
"citronfromage":{"a":"Ji-Elle","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Lemon_mousse-Sri_Lanka.jpg"},
"citronkage":{"a":"Kolforn (Kolforn) I'd appreciate if you could mail me (Kolforn@gmail.com) if you want to use this picture out of the Wikimedia project scope. This file is licensed under the Creative Commons Attribution-Share Alike 4.0 International license. You are free: to share – to copy, distribute and transmit the work to remix – to adapt the work Under the following conditions: attribution – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. share alike – If you remix, transform, or build upon the material, you must distribute your contributions under the same or compatible license as the original.https://creativecommons.org/licenses/by-sa/4.0CC BY-SA 4.0 Creative Commons Attribution-Share Alike 4.0 truetrue","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:-2010-01-31_Lemon_drizzel_cake,_Trimingham,_Norfolk_(1).JPG"},
"citrontaerte":{"a":"John","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Lemon_tart_-_star5112.jpg"},
"club-sandwich":{"a":"Memm","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Club-sandwich.jpg"},
"coleslaw":{"a":"Ukendt","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Bowl%27o%27Coleslaw_modified.jpg"},
"coq-au-vin":{"a":"Beck from East Midlands, United Kingdon","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Gourmet_coq_au_vin.jpg"},
"couscoussalat-med-kikaerter":{"a":"Karen and Brad Emerson","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Couscous_and_lentil_salad_(3658113458).jpg"},
"creme-br-lee":{"a":"Takeaway","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:2014_0531_Cr%C3%A8me_br%C3%BBl%C3%A9e_Doi_Mae_Salong_(cropped).jpg"},
"croque-monsieur":{"a":"Michael Brewer","l":"CC BY-SA 2.5","u":"https://commons.wikimedia.org/wiki/File:Croque_monsieur.jpg"},
"dadler-med-bacon":{"a":"Like_the_Grand_Canyon from Bochum, Germany","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:D%C3%A1tiles_con_bacon_-_detalle.jpg"},
"dahl-med-roede-linser":{"a":"AugustineKajur","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Dal_Tadka-Delhi.jpg"},
"droemmekage":{"a":"Cantons-de-l'Est","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:G%C3%A2teau_Reine_%C3%89lisabeth_-_pointe.jpg"},
"enchiladas-med-kylling":{"a":"Missvain","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_enchiladas_at_Frida%27s_Mexican_Grill_-_May_2023_-_Sarah_Stierch.jpg"},
"engelsk-morgenmad":{"a":"Acabashi","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Full_English_breakfast_at_Sainsbury%27s_Low_Hall,_Chingford,_London.jpg"},
"falafel":{"a":"やましこ","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Falafel_(49728839526).jpg"},
"fastelavnsboller":{"a":"Tomasz Sienicki [user: tsca, mail: tomasz.sienicki at gmail.com]","l":"CC BY 2.5","u":"https://commons.wikimedia.org/wiki/File:Fastelavnsboller_2_(ubt).jpeg"},
"fettuccine-alfredo":{"a":"Dllu","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_fettuccine_alfredo.JPG"},
"finskbroed":{"a":"Moonhouse","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Finska_pinnar.jpg"},
"fish-and-chips":{"a":"Matthias Meckel","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Fish_and_chips_blackpool.jpg"},
"fiskefrikadeller":{"a":"cyclonebill from Copenhagen, Denmark","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Grov_remoulade,_fiskefrikadeller,_salat_og_rugbr%C3%B8d_(6006379618).jpg"},
"fiskegratin":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Bill%27s_Fish_Pie_-_Bill%27s,_Lewes_2026-07-03.jpg"},
"fiskesuppe-med-safran":{"a":"Sergey A. Demidov","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:20250903_Bouillabaisse_in_Khimki_(26200).jpg"},
"flaeskesteg-med-roedkaal":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Fl%C3%A6skesteg_r%C3%B8dk%C3%A5l_brunede_kartofler.jpg"},
"focaccia":{"a":"Parkerman & Christie from San Diego, USA","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Rosemary_Focaccia.jpg"},
"forloren-hare":{"a":"Renee Comet (photographer)","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:MeatloafWithSauce.jpg"},
"fransk-loegsuppe":{"a":"jeffreyw","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Mmm...onion_soup_(5344349906).jpg"},
"franskbroed":{"a":"Mike Finn","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Tin_Loaf_-_one_slash_in_the_crust.jpg"},
"frikadeller":{"a":"Jacek Halicki","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:2023_Kotlety_mielone.jpg"},
"frittata-med-spinat-og-feta":{"a":"Deodora333","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:%D0%A4%D1%80%D0%B8%D1%82%D0%B0%D1%82%D0%B0_%D1%81%D0%BE_%D1%81%D0%BF%D0%B0%D0%BD%D0%B0%D1%9C_(02).jpg"},
"fyldte-peberfrugter-med-ris-og-feta":{"a":"Mark Bonica","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Quinoa_stuffed_peppers.jpg"},
"gammeldags-aeblekage":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Dansk_%C3%A6blekage.jpg"},
"gazpacho":{"a":"Juan Emilio Prades Bel","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Gazpacho_andaluz.jpg"},
"gnocchi-med-salvie-og-brunet-smoer":{"a":"Joy","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Sweet_potato_gnocchi_with_maple_sage_brown_butter_(4285979923).jpg"},
"graesk-salat":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Gr%C3%A6sk_salat.jpg"},
"graeskarsuppe-med-ingefaer":{"a":"Cala cala_maffia","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Autumn_Soup_(Unsplash)_cropped.jpg"},
"grahamsboller":{"a":"Fumikas Sagisavas","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:IKEA_wholemeal_rolls.jpg"},
"granola-med-noedder-og-ahornsirup":{"a":"Karen and Brad Emerson","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Homemade_granola_(12272245254).jpg"},
"groen-smoothie-med-spinat-og-banan":{"a":"Lablascovegmenu from London","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Green_smoothie_(8222465502).jpg"},
"groen-thaikarry-med-tofu":{"a":"PallaviKhale","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Thai_Green_Curry,JasminRice,Chilli_Basil_Chicken_,_HomeMade.jpg"},
"groenkaalssalat-med-aeble-og-tranebaer":{"a":"Cajsa Lilliehook from Portland","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Kale_%26_ChickPea_Salad_(8425128977).jpg"},
"grovboller":{"a":"cyclonebill from Copenhagen, Denmark","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Grovboller_(8706469249).jpg"},
"guacamole":{"a":"stu_spivack","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:El_tango_guacamole.jpg"},
"gulerodskage":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Carrot_cake_-_Milfey_Patisserie_2026-09-07.jpg"},
"gulerodssuppe-med-ingefaer":{"a":"James Cohen from San Francisco, U. S. of A.","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Carrot_ginger_soup_with_sesame_oil_garnish.jpg"},
"gullasch":{"a":"Valeva1010","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Hungarian_Goulash_Recipe.png"},
"hakkeboef-med-bloede-loeg":{"a":"User:Nillerdk","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Hakkeb%C3%B8ffer_bl%C3%B8de_l%C3%B8g_sovs_kartorfler.jpg"},
"hamburgerryg-med-floedekartofler":{"a":"Silar","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:02023_1239_Kassler.jpg"},
"havrecookies":{"a":"Paul Martin","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Oatmeal_Cookies_with_orange_zest,_golden_raisins,_and_chocolate_chips.jpg"},
"havregroed":{"a":"FitTasteTic","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Healthy_Oatmeal_with_Berries_-_49859913257.jpg"},
"helstegt-kylling-med-kartofler":{"a":"Michael J. Bennett","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Roasted_Chicken,_Butterflied,_on_Potatoes,_Baking_Pan_01.jpg"},
"hindbaersnitter":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Hindb%C3%A6rsnitte.jpg"},
"hjemmelavede-pommes-frites":{"a":"Tony Webster from Minneapolis, Minnesota, United States","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Truffle_oil_french_fries_(33024792848).jpg"},
"hjemmelavet-leverpostej":{"a":"RhinoMind","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Leverpostej_01.jpg"},
"hjemmelavet-pizza":{"a":"Mario56","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG"},
"hoensekoedssuppe-med-boller":{"a":"ralphhogaboom","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Soup_with_meatballs-01.jpg"},
"hoensesalat":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Sm%C3%B8rrebr%C3%B8d_med_h%C3%B8nsesalat.jpg"},
"huevos-rancheros":{"a":"1000b","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Huevos_rancheros.jpg"},
"hummus":{"a":"Vyacheslav Argenberg","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Lebanon,_Baalbek,_Lebanese_Hummus.jpg"},
"hveder":{"a":"Replayful","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Varme_hveder_med_smoer.jpg"},
"irsk-lammegryde":{"a":"Asmoo at German Wikipedia","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Irish_stew_2007_(cropped).jpg"},
"jambalaya":{"a":"Arnold Gatilao","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Jambalaya_-_3315899200.jpg"},
"joedekager":{"a":"Sindum","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:J%C3%B8dekage.jpg"},
"jordbaerlagkage":{"a":"Kimberly Vardeman from Lubbock, TX, USA","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Strawberry_Cream_Cake.jpg"},
"jordbaersorbet":{"a":"Ben Brophy","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Strawberry_sorbet.jpg"},
"jordskokkesuppe-med-persilleolie":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Jordskokkesuppe_med_ristede_kapers.jpg"},
"julekage":{"a":"Art Anderson","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Julekake_-_panoramio.jpg"},
"kalvefrikasse":{"a":"Gerda Arendt","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Veal_fricassee,_Steckenroth.jpg"},
"kanelsnegle":{"a":"Pannet","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Homemade_Cinnamon_rolls_06.jpg"},
"kanelstang":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Cinnamon_Roll_-_Olea_2025-07-03.jpg"},
"kardemommeknuder":{"a":"W.carter","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Cardamom_buns.jpg"},
"kartoffel-porresuppe":{"a":"jeffreyw","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Mmm..._potato_leek_soup_(5849815506).jpg"},
"kartoffelgratin-med-porrer":{"a":"Johnbrel","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Gratin_dauphinois_avr_20.jpg"},
"kartoffelmad-med-rosmarin":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Kartoffelmad_(1).jpg"},
"kartoffelsalat":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Kartoffelsalat_with_mayonnaise.jpg"},
"kikaertekarry-med-spinat":{"a":"Kari Sullivan from Austin, TX","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Spinach-Chickpea_Curry_(3117324894).jpg"},
"kladdkaka":{"a":"Andreas Ivarsson","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Kladdkaka-med-vispgradde.jpg"},
"klejner":{"a":"Yez Raphn from Bornholm, Denmark","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Klejner_yaz.jpg"},
"koedboller-i-tomatsauce":{"a":"HaJunkiyada","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Meatballs_in_tomato_sauce.jpg"},
"koftaspyd-med-tzatziki":{"a":"Anatolianpride","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Adana_kebab.jpg"},
"kokostoppe":{"a":"Rex Roof","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chocolate-bottomed_macaroons,_Janaury_2010.jpg"},
"koteletter-i-fad":{"a":"CharmaineZoe's Marvelous Melange from England","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pork_Chop_with_sweet_potato_mash_and_mushrooms_in_a_demerara_sauce._(36249946845).jpg"},
"krebinetter":{"a":"Interstates","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Karbonader_af_soy4you_med_kartoffelsalat.jpg"},
"kung-pao-kylling":{"a":"Steven G. Johnson","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Kung-pao-shanghai.jpg"},
"kylling-cacciatore":{"a":"Evan Joshua Swigart (TheCulinaryGeek)","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_cacciatore_(cropped).jpg"},
"kylling-cordon-bleu":{"a":"Rainer Zenz","l":"GPL","u":"https://commons.wikimedia.org/wiki/File:Cordon-bleu-2.jpg"},
"kylling-i-karry":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Kylling_i_karry_(1).jpg"},
"kylling-tikka-masala":{"a":"Lance Vanlewen","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_Tikka_Masala_on_White_Plate_with_Spoon.jpg"},
"kyllingebryst-i-fad-med-soltoerrede-tomater":{"a":"Cullen328","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Home_cooked_Chicken_Florentine_in_2021.jpg"},
"kyllingefajitas":{"a":"Missvain","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_fajitas_-_La_Hacienda_-_Sarah_Stierch.jpg"},
"kyllingefrikasse":{"a":"Daniela Kloth","l":"GFDL 1.2","u":"https://commons.wikimedia.org/wiki/File:18-10-20_MG_4656.jpg"},
"kyllingepasta-i-floedesauce":{"a":"Deodora333","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B8%D0%BB%D0%B5%D1%88%D0%BA%D0%BE_%D0%90%D0%BB%D1%84%D1%80%D0%B5%D0%B4%D0%BE.jpg"},
"kyllingeshawarma":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Chicken_Shawarma_Wrap_-_Lavash_2024-09-11.jpg"},
"kyllingespyd-med-satay":{"a":"Thank You (25 Millions ) views from Fresno, USA","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_Satay_(54029806221).jpg"},
"laks-i-ovn-med-citron":{"a":"MOs810","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Baked_salmon_with_dill_and_lemon.jpg"},
"lammekoelle-med-hvidloeg-og-rosmarin":{"a":"Beck","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Roast_lamb_leg.jpg"},
"lammetagine-med-abrikoser":{"a":"Kimberly Vardeman","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:African_Dinner.jpg"},
"lasagne":{"a":"jules / stonesoup","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Lasagne_-_stonesoup.jpg"},
"linsesalat-med-feta-og-mynte":{"a":"Joey Doll","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Lentil_salad_(29308018298).jpg"},
"lussekatte":{"a":"erik forsberg from Helsingborg, Sweden","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Lussekatter_1_(316623726).jpg"},
"mac-and-cheese":{"a":"Scott Veg","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Baked_macaroni_and_cheese_close-up.jpg"},
"marmorkage":{"a":"Fotographen: Thomas Högner Maximilian Högner (User:Leberwurscht)","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Marmorkuchen.jpg"},
"medisterpoelse-med-stuvet-hvidkaal":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Medisterp%C3%B8lse_med_tilbeh%C3%B8r.jpg"},
"mexicansk-tortillasuppe":{"a":"Wikiwrimo","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Tortilla_Soup.jpg"},
"millionboef-med-kartoffelmos":{"a":"Mutt Lunker","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Mince_an_tawties_(cropped).jpg"},
"minestrone":{"a":"Katrin Morenz from Aachen, Deutschland","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Minestrone_soup.jpg"},
"misosuppe-med-tofu":{"a":"Ocdp","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Miso_Soup_001.jpg"},
"moerbradboeffer-med-champignonsauce":{"a":"Nemracc","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Inn,_Gasthaus_Heinemann_in_Bremke-Gleichen.jpg"},
"moerbradgryde":{"a":"Christian Michelides","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Z%C3%BCrcher_Geschnetzeltes_mit_Sp%C3%A4tzle.jpg"},
"moussaka":{"a":"Key West Wedding Photography","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Moussaka_11.jpg"},
"naan":{"a":"OpenCage","l":"CC BY-SA 2.5","u":"https://commons.wikimedia.org/wiki/File:Naan_shiva.jpg"},
"nachos-med-ost":{"a":"روتانا","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Nachos_with_Melted_Cheese,_Jalapenos,_and_Tasty_Toppings.jpg"},
"natboller":{"a":"Dennis Lamczak","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Br%C3%B6tchen_(93753157).jpeg"},
"omelet-med-skinke-og-ost":{"a":"John Freeman","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Ham_%26_Cheddar_Omelet_(2)_(38273836121).jpg"},
"one-pot-pasta-med-tomat-og-spinat":{"a":"Mike Kniec from Manchester, UK","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:One_Pot_Pasta_(23029326055).jpg"},
"orecchiette-med-broccoli":{"a":"Romainbehar","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Lyon_7e_-_Restaurant_Veronatuti_-_Orecchiette_con_le_cime_di_rapa_(plat_originaire_des_Pouilles).jpg"},
"overnight-oats":{"a":"Nervy8924","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Protein_overnight_oats.jpg"},
"ovnbagte-groentsager-med-feta":{"a":"Mack Male from Edmonton, AB, Canada","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Roasted_Vegetables_(2897937502).jpg"},
"ovnkartofler-med-rosmarin":{"a":"Rooey202","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Roasted_Potato_Wedges_with_Shallots_and_Rosemary_(5706897999).jpg"},
"pad-thai":{"a":"Takeaway","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Phat_Thai_kung_Chang_Khien_street_stall.jpg"},
"paella":{"a":"Brillante","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Paella-mixta.jpg"},
"paeretaerte-med-marcipan":{"a":"Dainee Ranaweera","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Pear_and_Almond_Tart_at_St._Petrocs_Hotel.jpg"},
"palak-paneer":{"a":"DreamyFlutura11","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Palak_Paneer_(Cottage_cheese_in_spinach_gravy).jpg"},
"pandestegt-laks-med-dild":{"a":"CharmaineZoe's Marvelous Melange from England","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Salmon_Steak_with_boiled_new_potatoes,_asparagus,_hollandaise_%26_dill_sauces_(15980836317).jpg"},
"paneret-fiskefilet-med-remoulade":{"a":"Gerda Arendt","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Fish_dish,_Idstein.jpg"},
"panna-cotta":{"a":"JIP","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Raspberry_pannacotta_at_Inferno_Bar_Lund.jpg"},
"panzanella":{"a":"Missvain","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Sunday_Supper_Aug_2019_-_Stierch_04.jpg"},
"pariserboef":{"a":"Thomas Angermann from Copenhagen, Denmark","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Pariserb%C3%B8f_(5992637279).jpg"},
"pasta-all-amatriciana":{"a":"stu_spivack","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Bucatini_(amatriciana_rossa).jpg"},
"pasta-alla-norma":{"a":"Paoletta S.","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pasta_alla_Norma_(2563876877).jpg"},
"pasta-i-tomatsauce":{"a":"Silvimelo","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Spaghetti_al_pomodoro,_icona_della_cucina_italiana_nel_mondo._.jpg"},
"pasta-med-laks-og-spinat":{"a":"Jw2c","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Pasta_met_zalm_en_rucola.jpg"},
"pasta-med-pesto":{"a":"Paul Goyette","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Pasta_with_pesto.jpg"},
"pasta-med-rejer-hvidloeg-og-chili":{"a":"Wiki.cullin","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Linguine_with_Shrimp_on_a_round_plate.jpg"},
"pasta-med-salsiccia-og-fennikel":{"a":"Luca Nebuloni from Milan, Italy","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pici_with_sausage_(9870139783).jpg"},
"pasta-med-tun-og-citron":{"a":"Adry0104","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Spaghetti_with_tuna.jpg"},
"pasta-puttanesca":{"a":"Popo le Chien","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Pasta_Puttanesca.jpg"},
"pastasalat":{"a":"Brynn","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Pasta_salad_closeup.JPG"},
"patatas-bravas":{"a":"Francesc Fort","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Taberna_Che_-_Braves.jpg"},
"pavlova":{"a":"brett jordan","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pavlova_garnished_with_cream_and_strawberries.jpg"},
"pebernoedder":{"a":"M.Minderhoud","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Pepernoten001.jpg"},
"penne-all-arrabbiata":{"a":"Petar Milošević","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Penne_Arrabbiata.jpg"},
"pho-med-oksekoed":{"a":"Kham Tran","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Pho-Beef-Noodle-Soup-2008.jpg"},
"pita-med-grillet-halloumi":{"a":"Elyaqim Mosheh Adam אליקים משה אדם","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Grilled_halloumi,_%CE%A0%CE%BB%CE%AC%CE%BA%CE%B1,_31st_Ave.jpg"},
"pitabroed":{"a":"fugzu","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pita_Flatbread.jpg"},
"pizzasnegle":{"a":"NikiWiki im Koch-Wiki","l":"CC BY-SA 3.0 de","u":"https://commons.wikimedia.org/wiki/File:Pizzaschnecken-klein.jpg"},
"poelseret-med-bacon":{"a":"Blockhaj","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Korvstroganoff_in_pan.jpg"},
"pulled-pork":{"a":"Christian Geischeder","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Pulled_pork_008.jpg"},
"quesadillas":{"a":"Photograph by Mike Peel (www.mikepeel.net).","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:At_Long_Island_2023_267.jpg"},
"quinoasalat-med-avocado-og-limedressing":{"a":"Geoff Peters from Vancouver, BC, Canada","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Quinoa_Salad_(5045982815).jpg"},
"rabarbertaerte":{"a":"Colonel Warden at English Wikipedia","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Rhubarb_tart.jpg"},
"ramen-med-kylling":{"a":"Daderot","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Chicken_ramen_-_London,_UK.jpg"},
"ratatouille":{"a":"Arnaud 25","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Ratatouille_001.jpg"},
"rejecocktail":{"a":"see below.","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Cocktail_1_bg_060702.jpg"},
"rejer-i-hvidloegsolie":{"a":"Juan Emilio Prades Bel","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Las_gambas_al_ajillo,_t%C3%ADpica_tapa_espa%C3%B1ola.jpg"},
"rejer-med-hvidloeg-og-chili":{"a":"Javier Lastras from España/Spain","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Gambas_al_ajillo.jpg"},
"risalamande":{"a":"Lorie Shaull","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Risalamande,_a_Danish_Christmas_dessert.jpg"},
"ristede-kikaerter-med-paprika":{"a":"Physicistjedi","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Leblebi.jpg"},
"roedbedesalat-med-gedeost-og-valnoedder":{"a":"Chris Olszewski","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Beetroot,_spinach,_rocket,_goat_cheese_and_pumpkin_seeds_salad.jpg"},
"roedkaal":{"a":"MOs810","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Modra_kapusta_po_poznansku.jpg"},
"roeget-laks-med-roeraeg-paa-rugbroed":{"a":"Missvain","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Buckeye_Roadhouse_-_Feb_2019_-_Sarah_Stierch_04.jpg"},
"roeraeg-med-purloeg":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Rugbr%C3%B8d_med_peberkippers_og_r%C3%B8r%C3%A6g.jpg"},
"rosinboller":{"a":"smial (talk)","l":"FAL","u":"https://commons.wikimedia.org/wiki/File:Minikrentenbollen_IMGP6988_wp.jpg"},
"roulade-med-syltetoej":{"a":"Ocdp","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Swiss_roll_003.jpg"},
"rugbroed-med-kerner":{"a":"Glane23","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Dark_rye_bread.JPG"},
"salade-ni-oise":{"a":"Daderot","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Salade_ni%C3%A7oise_variant_-_Massachusetts.jpg"},
"sandkage":{"a":"Douglas Paul Perkins","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Pound_cake_1.jpg"},
"sandwich-med-kylling-og-pesto":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:CIABATTA_-_Vios_2025-08-08.jpg"},
"scones":{"a":"Alpha from Melbourne, Australia","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Scones_Jam_Cream.jpg"},
"shakshuka":{"a":"HaJunkiyada","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Classic_Red_Shakshuka_with_Egg.jpg"},
"shepherd-s-pie":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Shepherds_pie_-_The_Kew_Greenhouse_Cafe_2025-05-14.jpg"},
"skipperlabskovs":{"a":"Valereee","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Lobscouse,_Lobby,_Scouse.jpg"},
"smoerkringle":{"a":"Øyvind Holmstad","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Stor_kringle_-_big_pastry.JPG"},
"smoothie-bowl":{"a":"Ella Olsson from Stockholm, Sweden","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Acai_bowl_(43110767814).jpg"},
"soed-kartoffel-og-linsegryde":{"a":"Whoisjohngalt","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Bowl_of_lentil_soup_with_green_and_red_lentils.jpg"},
"sort-boennesuppe":{"a":"newton64","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Black_bean_soup.jpg"},
"spaghetti-aglio-e-olio":{"a":"Bairuilong","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Spaghetti_aglio_e_olio_KB.jpg"},
"spaghetti-alle-vongole":{"a":"Alpha from Melbourne, Australia","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Spaghetti_alle_vongole,_Cafe_a_Taglio,_St._Kilda.jpg"},
"spaghetti-bolognese":{"a":"Chingon","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Spaghetti_Bolognese.jpg"},
"spaghetti-carbonara":{"a":"Javier Somoza","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Espaguetis_carbonara.jpg"},
"spandauer":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Spandauer_med_creme.JPG"},
"speltboller":{"a":"Katrin Gilger","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Br%C3%B6tchen_(4486871839).jpg"},
"spinatsalat-med-jordbaer-og-feta":{"a":"Vancouver Bites! from Vancouver, Canada","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Strawberry_Spinach_Salad_(5000511898).jpg"},
"stegt-flaesk-med-persillesovs":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Stegt_fl%C3%A6sk_med_persillesovs.jpg"},
"stegte-roedspaetter-med-persillesmoer":{"a":"Benreis","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Scholle_gebraten_Kaputh.jpg"},
"stjerneskud":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Sm%C3%B8rrebr%C3%B8d_4.jpg"},
"svamperisotto":{"a":"spurekar","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Mushroom_and_Leek_Risotto_(49535206656).jpg"},
"svenske-koedboller-med-floedesovs":{"a":"Ralf Roletschek","l":"GFDL 1.2","u":"https://commons.wikimedia.org/wiki/File:17-06-09-IKEA-K%C3%B6ttbullar-RalfR-IMG_20170609_182055_928a.jpg"},
"svinekoed-i-soed-sur-sauce":{"a":"Walter Grassroot","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:%E8%8F%A0%E8%90%9D%E5%92%95%E5%99%9C%E8%82%89.jpg"},
"syltede-roedloeg":{"a":"Kotivalo","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Pickled_red_onion_in_jar.jpg"},
"tabbouleh":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Tabbouleh.jpg"},
"tacos":{"a":"Daderot","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Tacos_with_ground_beef_-_Massachusetts.jpg"},
"taerte-med-porre-og-gedeost":{"a":"Katrin Gilger","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Quiche_with_Potatoes,_Leek,_Bacon_%26_Wine_(4876354744).jpg"},
"tagliatelle-med-svampe-og-timian":{"a":"Syced","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Mushroom_tagliatelle_at_Japanese_Italia-inspired_family_restaurant.jpg"},
"tarteletter-med-hoens-i-asparges":{"a":"Richard N Horne","l":"CC BY 4.0","u":"https://commons.wikimedia.org/wiki/File:Seafood_Vol-au-vent.jpg"},
"tebirkes":{"a":"cyclonebill","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Tebirkes.jpg"},
"teriyakikylling":{"a":"Flickr.com user \"Blue Lotus\"","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_teriyaki.jpg"},
"teriyakitofu-med-ris":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Vegan_teriyaki_rice_(M)_-_Goemon_Ramen_Bar_2025-04-14.jpg"},
"thailandsk-nudelsalat-med-kylling":{"a":"tomatoes and friends","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Vegan_Vietnamese_Rice_Noodle_Salad_with_Tofu_(7242352372).jpg"},
"thailandsk-roed-karry-med-kylling":{"a":"Guilhem Vellut from Paris, France","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Red_chicken_curry,_Aiyara_Thai_restaurant,_Paris_001.jpg"},
"tiramisu":{"a":"Sharon Chen from Austin, United States","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Classic_Italian_Tiramisu-3_(29989504485).jpg"},
"toastbroed":{"a":"loppear","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Pullman_loaf.jpg"},
"tom-kha-gai":{"a":"lydiajoy1","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Tom_kha_gai2.jpg"},
"tom-yum-med-rejer":{"a":"JIP","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Tom_yum_goong_at_Thai_Orchid_Villa_Kamppi.jpg"},
"tomatsuppe":{"a":"Thriving Vegetarian","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Tomato_Basil_Bisque_-_12863421225.jpg"},
"torsk-i-ovn-med-sennepssauce":{"a":"Benreis","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Kuhler_Pannfisch.jpg"},
"tortilla-espanola":{"a":"Juan Emilio Prades Bel","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Tortilla_Espa%C3%B1ola.jpg"},
"tunsalat-paa-rugbroed":{"a":"U.S. Department of Agriculture","l":"Public domain","u":"https://commons.wikimedia.org/wiki/File:Tuna_fish_sandwiches_for_the_National_School_Lunch_Program_(1).jpg"},
"tynde-pandekager":{"a":"David Monniaux","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Crepes_dsc07085.jpg"},
"tyrkisk-linsesuppe":{"a":"E4024","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:Mercimek_%C3%A7orbas%C4%B1_in_Ankara,_Turkey.jpg"},
"tyrkiske-aeg-med-yoghurt-og-chilismoer":{"a":"Andy Li","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:%C3%87%C4%B1lb%C4%B1r_-_Cafe_Rust_2025-03-31.jpg"},
"tysk-kartoffelsalat-med-bacon":{"a":"Oxfordian Kissuth","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Kartoffelsalat_als_Specksalat.jpg"},
"tzatziki":{"a":"Nikodem Nijaki","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Tzatziki_IMGP1480.jpg"},
"vaniljeis":{"a":"a.pasquier from bellingham, washington","l":"CC BY-SA 2.0","u":"https://commons.wikimedia.org/wiki/File:Vanilla_bean_ice_cream_(3086700978).jpg"},
"vaniljekranse":{"a":"sdnet01","l":"CC0","u":"https://commons.wikimedia.org/wiki/File:Danish-butter-cookies_(ring-shaped).jpg"},
"varm-artiskokdip":{"a":"Famartin","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:2019-02-25_19_29_06_A_bowl_of_spinach-artichoke_dip_at_the_Applebee%27s_in_Fair_Lakes,_Fairfax_County,_Virginia.jpg"},
"vegetarisk-shepherd-s-pie":{"a":"Abhinaba Basu from Redmond, United States","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Shepherd%27s_pie_(22470901009)_(cropped).jpg"},
"vegetarlasagne-med-spinat-og-ricotta":{"a":"Magalia","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Tort_warzywny.JPG"},
"waldorfsalat":{"a":"Nillerdk","l":"CC BY 3.0","u":"https://commons.wikimedia.org/wiki/File:Waldorfsalat.jpg"},
"wienerschnitzel":{"a":"Burkhard Mücke","l":"CC BY-SA 4.0","u":"https://commons.wikimedia.org/wiki/File:2022-12-29_Wiener_Schnitzel_im_Hotel_Kaiserin_Elisabeth.jpg"},
"wok-med-kylling-og-groentsager":{"a":"Yummy O Yummy","l":"CC BY 2.0","u":"https://commons.wikimedia.org/wiki/File:Chicken_and_Vegetable_Stir-Fry_(15914100572).jpg"},
"wraps-med-kylling-og-hvidloegsdressing":{"a":"Takeaway","l":"CC BY-SA 3.0","u":"https://commons.wikimedia.org/wiki/File:Smoked_chicken_and_avocado_wrap.jpg"}};
